### ISSUE TITLE
:not keyword in _has search parameters do not works

### ISSUE THREAD

**Issue by lemsy** [Aidbox/Issues#102]
We try to obtain DiagnosticReports related to Task that doesn't has a completed status. We make this query:

`get /fhir/DiagnosticReport?_has:Task:status:not=completed`

but we get

```
resourceType: OperationOutcome
status: 422
issue:
- {severity: error, code: invalid, diagnostics: No search parameter for Task.not}

```
We use other server and the query works, ej: http://test.fhir.org/r4/DiagnosticReport?_format=json&_has:Task:status:not=completed

**Comment by niquola** [comment]
Should be fixed in 0.4.4-SNAPSHOT in 15 min
