### ISSUE TITLE
Bundle.total response unexpected value

### ISSUE THREAD

**Issue by jyeros** [Aidbox/Issues#105]
When i do a get to a resource, bundle.total return unexpected value(i think it return the number of resources).
For example if i do `Get /Patient?_count=1` i expect the total should be <=1, but i get the total of resources in patient and if i do `Get /Patient` the total instead 100 is the same.

**Comment by niquola** [comment]
By definition of total, you have to get a total number of matches for a query without paging. Is that, what do you see? For example, if you have 5K patients in database `GET /Patient`  .total should be 5K

**Comment by jyeros** [comment]
Yes, it was the wrong issues, the issue was related to the include that return the total of the element plus the total of the include resorce.
According to that reference we should get the total amount of matches. Thanks for fixing
