### ISSUE TITLE
Search by date with `+` return 500

### ISSUE THREAD

**Issue by jyeros** [Aidbox/Issues#106]
The date format is 
`yyyy-mm-ddThh:mm:ss[Z|(+|-)hh:mm`
It has 3 options
  - `yyyy-mm-ddThh:mm:ssZ` :white_check_mark: 
  - `yyyy-mm-ddThh:mm:ss-hh:mm` :white_check_mark: 
  - `yyyy-mm-ddThh:mm:ss+hh:mm` :x: 

If i search using the first 2 options the server response ok. But if i use the third option the server response with status code 500 and message
```
resourceType: OperationOutcome
id: exception
text: {status: generated, div: 'ERROR: invalid input syntax for type timestamp with time zone: "2019-05-30T17:15:30.039521 01:00"'}
issue:
- {severity: fatal, code: exception, diagnostics: 'ERROR: invalid input syntax for type timestamp with time zone: "2019-05-30T17:15:30.039521 01:00"'}
```
The `+` isn't at the error message

**Comment by niquola** [comment]
You have to escape `+` sign in parameter value - use   `yyyy-mm-ddThh:mm:s%2Bhh:mm`, i.e.  try `2019-05-30T17:15:30.039521%2B01:00`

**Comment by jyeros** [comment]
Thanks, I escape it and work well.
