### ISSUE TITLE
Unable to use _has and _sort at the same time

### ISSUE THREAD

**Issue by jyeros** [Aidbox/Issues#107]
If i use only `_has` the server response ok equals if i use only `_sort` but if i use both together the server response with status code 500 and message
```
resourceType: OperationOutcome
id: exception
text:
  status: generated
  div: |-
    ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list
      Position: 307
issue:
- severity: fatal
  code: exception
  diagnostics: |-
    ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list
      Position: 307
```
sumary
  - `Get /DiagnosticReport?_has:Task:based-on:status=requested` :white_check_mark: 
  - `Get /DiagnosticReport?_sort=issued` :white_check_mark: 
  - `Get /DiagnosticReport?_has:Task:based-on:status=requested&_sort=issued` :x: statusCode 500 and message showed above

**Comment by niquola** [comment]
Should be fixed in 0.4.5, if not reopen please
