### ISSUE TITLE
Wrong redirect to identity provider if configuration does not exists

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#112]
If no configuration is provided to Aidbox it creates empty configurations for Google or Github, then if you try to login with one of those, the redirect to the identity providers goes with empty `client_id` since it is not in the configurations. I think Aidbox should show an error page to inform that a configuration should be provided, and maybe it should not create a configuration if it is not provided.

**Comment by niquola** [comment]
Done in 0.4.5-SNAPSHOT - if no env for the provider - do not create config at all
Probably in aidbox db you have to do cleanup:
```sql
update _box set resource = resource - 'resources'
```
