### ISSUE TITLE
Same resource repeated in the response

### ISSUE THREAD

**Issue by lemsy** [Aidbox/Issues#118]
We want to recover `Tasks` related to `Specimens` by the `receivedTime` field. We have defined a new SearchParameter for `receivedTime` named `Specimen.received` since it did not exist before. And make the query `get /fhir/Task?based-on:RequestGroup.target:ServiceRequest.specimen:Specimen.received=2019-05-13`. In the response we see several `Tasks` with the same `id`, in other words, the same `Task`.

**Comment by niquola** [comment]
Can you provide example data of RequestGroup? is RequestGroup.target your custom search parameter too?

**Comment by niquola** [comment]
I've pushed first fix. Will be published in 10 minutes. But I need to spend some time on refactoring - so the final version will be tomorrow.
