### ISSUE TITLE
Resource included into results even if its date should not match (miliseconds)

### ISSUE THREAD

**Issue by jyeros** [Aidbox/Issues#124]
`Get /Task?authored-on=lt2019-07-03T02:28:57.3042803%2B00:00`
and we have this resource at db, and the server response with the resource. It work with other dates 😕, we try to change the number after `.` and there are something rare, sometimes work and sometime doesn't
```
{
 "intent": "order",
 "status": "requested",
 "authoredOn": "2019-07-03T02:28:57.3042803+00:00",
 "id": "d9e93c05-4be7-4afd-8d50-955d1566ca39",
 "resourceType": "Task"
}
```
The problem is that resource included into results even if its date should not match (miliseconds).
In this case is because are the same date and the query is less than. There is other case when the date is less and the resource are in the result, for example:
```
resource date: 2019-07-03T02:28:57.3042823+00:00
query: authored-on=lt2019-07-03T02:28:57.3042803%2B00:00
```
and the resource is in the result

**Comment by ruscoder** [comment]
@niquola I also encountered this issue. Could you please double-check how `lt` works? In aidbox 0.4.0 `lt` worked in another way. 
Query: GET /Task?period-start=ge2019-07-22T21:00:00Z&period-start=lt2019-07-23T21:00:00Z
returns even Task with period.start=2019-07-23T21:00:00Z in aidbox 0.4.5+.
(Note: period-start is custom SearchParameter with expression [[period, start]])

0.4.0
```
['SELECT "task".* FROM "task" WHERE (knife_extract_min_timestamptz("task".resource,
    ?) >= knife_date_bound(?, ?) AND knife_extract_min_timestamptz("task".resource,
    ?) < knife_date_bound(?, ?)) LIMIT ? OFFSET ?', '[["executionPeriod","start"]]',
  '2019-07-22T21:00:00Z', min, '[["executionPeriod","start"]]', '2019-07-23T21:00:00Z',
  min, 100, 0]
```

0.4.5
```
['SELECT "task".* FROM "task" WHERE (knife_extract_max_timestamptz("task".resource, ?) >= knife_date_bound(?, ?) AND 
knife_extract_min_timestamptz("task".resource, ?) < knife_date_bound(?, ?)) LIMIT ? OFFSET ? ', '[["executionPeriod","start"]]', '2019-07-22T21:00:00Z', min, '[["executionPeriod","start"]]', '2019-07-23T21:00:00Z', max, 100, 0]
```

**Comment by niquola** [comment]
SQL expression is right - we use "greedy " approach trying to match as much resources as possible. I will debug postgresql extension today for milliseconds handling.

**Comment by niquola** [comment]
Can you provide exactl values of timestamps in resources and in search param, which does not work properly?

**Comment by niquola** [comment]
Hey guys, can you test it with new aidboxdb build -  `aidbox/db:11.4.0-RC5`

**Comment by niquola** [comment]
Now i'm looking at generated sql and understand it's anti-greedy :( - gonna fix it in aidbox

**Comment by ruscoder** [comment]
> Can you provide exact values of timestamps in resources and in search param, which does not work properly?
In db period.start = 2019-07-23T21:00:00.000Z and I get this Task for query ?period-start=lt2019-07-23T21:00:00Z

**Comment by niquola** [comment]
Does it works with new aidbox/db?
