### ISSUE TITLE
_revinclude=* returns the same resources as _include=*

### ISSUE THREAD

**Issue by ivangalban** [Aidbox/Issues#126]
`_revinclude=*` it does not work correctly. For example:

`GET /fhir/Patient?_id=[id]&_revinclude=*` returns the same resources  as ` GET /fhir/Patient?_id=[id]&_include=*`

**Comment by niquola** [comment]
Than you. We do not support _revincude=* because of essential performance penalty.  I will make aidbox report it.

**Comment by ivangalban** [comment]
@niquola  There is some idea for the future of supporting this even if it is very inefficient, maybe specifying a flag like `i_understand_the_risks` for example ?

**Comment by niquola** [comment]
I will think about this :) 

With Patient?_revinclude=* you will query half of the database - i.e. run more than 100 queries.

What is your use case for revinclude=*?

Probably you have to take a look at  https://docs.aidbox.app/tutorials/compartments

**Comment by ivangalban** [comment]
> I will think about this :)

ok, thanks

>With Patient?_revinclude=* you will query half of the database - i.e. run more than 100 queries.

true, although I was thinking about using `_revinclude=*` only from a particular instance

**Comment by niquola** [comment]
Not going implement this in the near future. Try again in half-year :)
