### ISSUE TITLE
Lack of documentation for Reference entity

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#131]
Quick doc about Reference which located at `[instance]/static/console.html#/entities/Attribute?entity=Reference` have some unclear points:

1. `Reference.id` is described as _"Unique id for inter-element referencing"_, but it is not mentioned that it refers to reference's **target** ID but not the reference's itself
2. Non-FHIR fields `resourceType` and `uri` have not description at all, seems that the only place about these fields is [here](https://docs.aidbox.app/basic-concepts/aidbox-vs-fhir#references)
3. Non-FHIR field `resource` has neither description, not even type

**Comment by niquola** [comment]
Fixed in 0.4.7-SNAPSHOT
