### ISSUE TITLE
_format=yaml doesn't work for /ValueSet

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#133]
Endpoint `/ValueSet/XXX/$expand?count=10` always returns JSON response, adding `_format=yaml` parameter has no effect.
Docker image version is `healthsamurai/devbox:0.4.6-SNAPSHOT`.

**Comment by KGOH** [comment]
Could not reproduce on edge, probably fixed long time ago 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/11963737/154025914-fd2f2a4a-32c4-4122-b794-24f9e4a9b778.png">
<img width="752" alt="image" src="https://user-images.githubusercontent.com/11963737/154025956-d2819427-b8ca-4ac1-8bae-63a7e9c10fe2.png">
