### ISSUE TITLE
Inconvenient redirect after deleting valueset entry

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#137]
1) Open any valueset description, i. e., `/static/console.html#/entities/Concept?valueset=observation-codes`
2) Open any entry and delete it with "delete" button
3) Entry is deleted and browser is redirected to `/static/console.html#/entities/Concept` so one needs to make search valueset again to continue working with it.

**Comment by niquola** [comment]
Sorry, not so trivial to fix
