### ISSUE TITLE
Allow to create index per day when using Aidbox CLI

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#142]
Is it possible to configure aidbox-cli to add a date to the index name, so instead of having a fixed name like this: `args: ["es", "logs", "-l", "http://elasticsearch-master:9200/aidbox/logs", "-f", "/logs/aidbox-logs.ndjson"]` it could create an index per day. The reason to do this is that ES have limits per index, and there is an approach of creating an index per day and then using patterns to join all those index. It's better performant and it's more easy to do maintenance that way.

**Comment by niquola** [comment]
Fixed in cli-RC1:

replace `http://elasticsearch-master:9200/aidbox/logs` with `http://elasticsearch-master:9200/aidbox`
and image version with `aidbox/aidbox-cli:0.0.1-RC1`

index name will be postfixed with a date like this `aidbox-2019-09-01`
