### ISSUE TITLE
Appointment.participant cardinality 

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#149]
Original FHIR declares that `Appointment.participant` has `1..*` values, but the following request succeeded:
```
PUT /Appointment/test-appointment

status: pending
participant: []
```
fhir-4.0.0 @ healthsamurai/devbox:0.4.6-SNAPSHOT

**Comment by KGOH** [comment]
Not a bug
https://github.com/HealthSamurai/sansara/issues/671#issuecomment-973993162
