### ISSUE TITLE
FHIR R4 missing search parameter ValueSet.context-type-value

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#169]
Aidbox 0.4.6

**Comment by niquola** [comment]
There is no such search parameter in FHIR downloads - please create it manually and report to FHIR community

**Comment by niquola** [comment]
I see it is on documentation :( but not in FHIR meta

**Comment by ruscoder** [comment]
I think it is because this search param has composite type. All composite search params are not defined in meta (checked on this resource). I don’t need this feature at the moment, this issue was just a notification
