### ISSUE TITLE
Token expiration detection at console

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#176]
If auth token becomes invalid while using AidBox console (e. g., server was restarted), it can be detected at REST console (message `{message: No session for this bearer token}` appears), but all other pages become unusable - DB console, 'Auth client' list and others just show blank response part. REST console log also shows empty history. Better way is to redirect to auth page when bad token is detected.

**Comment by KGOH** [comment]
@kzotoff, Please confirm if this is still relevant issue

**Comment by kzotoff** [comment]
@KGOH as of version 2111 console now redirects to login form
