### ISSUE TITLE
REST console needs request sequence numbering

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#177]
1) make first request which takes long time, i. e., terminology import from remote service
2) make some simple request quickly
3) first, you'll see response to the second request, then it will be overwritten with the first request result

**Comment by KGOH** [comment]
Couldn't reproduce on edge, probably fixed in 2107 release
<img width="594" alt="image" src="https://user-images.githubusercontent.com/11963737/154027778-68ab54fe-d1ed-4e2a-b4a6-fb016059e182.png">
