### ISSUE TITLE
Same repeated results are returned when using _revinclude:iterate

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#202]
I have a query like:
`
GET /fhir/PractitionerRole?practitioner=pract1&_include=organization&_revinclude:iterate=Organization:partof:Organization` where I'm getting the organizations that are related to a PractitionerRole, I also want the organizations that are part of the ones related to the PR. If I execute the above query I get the related orgs and the first level children. I want to search for another levels, so I added the `_revinclude:iterate=Organization:partof:Organization` again to the query but Aidbox is returning the first level children repeated as many times I add the `_revinclude` and not the children of thoses.

**Comment by vganshin** [comment]
Actually you don't need to repeat the same _revinclude:iterate param to get next level. It should work recursively. A bug is somewhere here.

BTW, let me clarify one thing. It looks like you gonna request whole tree of sub-organizations for just one practitioner role. Do you really have to retrieve all sub-organizations and not to get parent organizations for this one? The result set may be a bit huge.

**Comment by yosbeleg89** [comment]
Yes, just the sub-organizations of the organizations of practitioner roles related to a practitioner. We know for sure that in our case the tree will not be too huge.

Thanks

**Comment by vganshin** [comment]
Done in latest 0.4.8 build
