### ISSUE TITLE
_revinclude:iterate not working

### ISSUE THREAD

**Issue by guillerglez88** [Aidbox/Issues#215]
```
GET /RequestGroup
    ?_id=reqgroup1
    &_include=patient,author
    &_include:iterate=RequestGroup:target:MedicationRequest
    &_include:iterate=MedicationRequest:medication
    &_include:iterate=MedicationRequest:requester:PractitionerRole
    &_include:iterate=MedicationRequest:intended-performer:Organization
    &_include:iterate=PractitionerRole:practitioner
    &_include:iterate=Patient:organization
    &_include:iterate=PractitionerRole:location
    &_revinclude:iterate=AllergyIntolerance:patient
```
doesn't return any AllergyIntolerance in the response, however the following query works as expected:
```
GET /Patient
  ?_id=pat1
  &_revinclude=AllergyIntolerance:patient
```

RequestGroup.patient from the first query is same as second one: pat1

**Comment by niquola** [comment]
Can you try this query without  `:iterate` modifiers?

```yaml
GET /RequestGroup
    ?_id=reqgroup1
    &_include=patient,author
    &_include=RequestGroup:target:MedicationRequest
    &_include=MedicationRequest:medication
    &_include=MedicationRequest:requester:PractitionerRole
    &_include=MedicationRequest:intended-performer:Organization
    &_include=PractitionerRole:practitioner
    &_include=Patient:organization
    &_include=PractitionerRole:location
    &_revinclude=AllergyIntolerance:patient
```

**Comment by guillerglez88** [comment]
Sure, I let you know in a couple minutes.

**Comment by guillerglez88** [comment]
@niquola , worked! Thank you. I tried: 
✅  removing `:iterate` and appending `:Patient` 
❌ only removing `:iterate`
✅ only appending `:Patient`

why is it required to append `:Patient` , AllergyIntolerance.patient is not polymorphic
![image](https://user-images.githubusercontent.com/8441801/69639226-285bd800-102a-11ea-9979-6e2344f88e24.png)

**Comment by niquola** [comment]
I started discussion in fhir chat - https://chat.fhir.org/#narrow/stream/179166-implementers/topic/About.20_include.3Aiterate
