### ISSUE TITLE
Support for Observation/$lastn in compartments

### ISSUE THREAD

**Issue by orlandow** [Aidbox/Issues#23]
```
┌────
│ GET /Patient/pat1/Observation/$lastn?category=vital-signs
└────

┌────
│ {
│   "message": ":get /Patient/pat1/Observation/$lastn not found"
│ }
└────
```

I'm not sure if it's specced like this in fhir but we want to use compartments for all patient access from the app (makes auth rules easier to define)

**Comment by mlapshin** [comment]
implemented in version `0.3.3-121-gdb5bde6`
