### ISSUE TITLE
:missing works wrong for null values

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#230]
Hello! I've encountered to the strange behaviour. Aidbox allows to save resource with nulls:
```
PUT /Patient/test

id: test
name: null
```

As a result, :missing works wrong - `GET /Patient?_id=test&name:missing=true` does not return the patient

but if we have the patient without a name
```
PUT /Patient/test

id: test
```

`GET /Patient?_id=test&name:missing=true` returns the patient.

Is it a bug?

FYI
```
select  knife_extract('{"name": null}', '[["name"]]'); -- ["null"]
select  knife_extract('{}', '[["name"]]'); -- null
```

But
```
select  ('{"name": null}'::jsonb)#>>'{name}' is null;  -- TRUE
select  ('{}'::jsonb)#>>'{name}' is null;  -- TRUE
```

**Comment by niquola** [comment]
We fixed this from other side - now aidbox strip empty values like nulls, empty objects and arrays on CRUD
