### ISSUE TITLE
Empty array silent auto-deletion

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#249]
Let's assume we want to create resource with array-type field containing empty array:
```
PUT /Composition/composition-123456789

{
  "section": [
    {
      "id": "100",
      "entry": []
    }
  ],
  ...
```
Request is successful at both versions I've checked - 0.4.8 and 0.4.9.

Now check out the resource:
`GET /Composition/composition-123456789`

Result at version devbox; 0.4.8-SNAPSHOT; 684d8564
```
id: composition-123456789
section:
- id: '100'
  entry: []
resourceType: Composition
...
```
Element `section[0].entry` is at its place.
Now result at version devbox; 0.4.9-SNAPSHOT; 62fdb2fb
```
id: composition-123456789
section:
- {id: '100'}
resourceType: Composition
...
```
As can be seen, empty `section[0].entry` silently removed from the resource.

It would be better that Aidbox either keep such element as it came from request or prevent saving the resource at all.

**Comment by niquola** [comment]
Fixed. Now we delete only `null`s
