### ISSUE TITLE
WebHook isn't working when creating an empty resource type

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#25]
According to the [documentation](https://docs.aidbox.app/api/subscriptions#rest-hook), if a subscription is created using as criteria (for example) `Patient`:

```
POST -> /fhir/Subscription

{
  "criteria": "Patient",
  "reason": "test",
  "channel": {
    "payload": "application/fhir+json",
    "type": "rest-hook",
    "endpoint": "http://requestbin.fullcontact.com/190v2dy1"
  },
  "resourceType": "Subscription",
  "status": "active"
}
```

When a `Patient` is created then the webhook should send the notification to the specified endpoint, if we create an empty `Patient` then the notification is not being sent:

```
POST -> /fhir/Patient

{
	"resourceType": "Patient",
}
```

**Comment by mlapshin** [comment]
Please try version `0.3.3-118-g02b3ac2`, it should be fixed as well as db connection leaks (timing out requests).

**Comment by yosbeleg89** [comment]
Yep, @mlapshin it is working on that version, thanks.
