### ISSUE TITLE
REST console caching

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#253]
TL;DR: rest console can use cached results from another result type

How to reproduce:
1) Open REST console, set [ YAML | JSON ] switch to "YAML" and request any `Patient`:
```
GET /Patient/id-1
```
Result:
```
resourceType: Patient
id: id-1
...
```

2) Set the switch to "JSON" position. Make request again. Now result will be:
```
Error: #object[SyntaxError SyntaxError: Unexpected token m in JSON at position 0]
resourceType: Patient
id: id-1
...
```
3) Open developer console and disable caching. Make request again. Now result will be at JSON format.

**Comment by KGOH** [comment]
Fixed
