### ISSUE TITLE
Casing issue with compartment definitions

### ISSUE THREAD

**Issue by orlandow** [Aidbox/Issues#26]
Compartments are using the definitions' id to create the url, this is causing this definition https://www.hl7.org/fhir/compartmentdefinition-patient.html to not work with this url: `Patient/pat1/Observation` but work with `patient/pat1/Observation`

We think that aidbox should use the `CompartmentDefinition.code` field as the url prefix or normalize the casing

**Comment by mlapshin** [comment]
I know that specs says to use `CompartmentDefinition.code` for compartment lookups, but there is no way to enforce uniqueness of `CompartmentDefinition.code` so I decided to use `id` to avoid disambiguation. Case normalization should resolve the problem.

**Comment by orlandow** [comment]
ok, 👍
