### ISSUE TITLE
App/addon subscriptions: wrong action for upsert

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#261]
When I'm, trying to create new User with new id (generated uuid)
```
PUT /User/newid
```

In DB we have status `created`, but in subscription, we have `update` action instead of `create`.

Is it expected behavior?

**Comment by niquola** [comment]
Yep, this is a bug

**Comment by KGOH** [comment]
@ruscoder couldn't reproduce. Do you still have this problem?
