### ISSUE TITLE
Frequent requests at REST console break it down

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#266]
Open REST console, write some request, i. e. `GET /Task` and send it several times frequently. After some requests console behavior changes: any new request output appends to previous one results (see screenshot) instead replacing it. Also message can be seen at developer console: _Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'._

![image](https://user-images.githubusercontent.com/13145399/75653036-af45cf80-5c6d-11ea-892a-056b309ddc74.png)

**Comment by rublag** [comment]
Can not reproduce.
