### ISSUE TITLE
Searching token with system does not works

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#271]
When searching by telecom (token), something like `/Practitioner?telecom=email|somemail@mail.com` does no return any value. If we omit the system then it works.
It also works if we use the email Search Parameter

**Comment by KGOH** [comment]
Hi. According to [fhir search api](https://www.hl7.org/fhir/search.html#token) you shouldn't search telecom with system:

> For token parameters on elements of type ContactPoint, uri, or boolean, the presence of the pipe symbol SHALL NOT be used - only the [parameter]=[code] form is allowed

While this `/Practitioner?telecom=work|somemail@mail.com` works in aidbox. @niquola should we forbid to search Contact point with "use"?

**Comment by yosbeleg89** [comment]
Hi
>According to fhir search api you shouldn't search telecom with system:

I see 🤔 

It could be useful, but we have `email` and `phone` search parameters for most important cases.
