### ISSUE TITLE
Aidbox modifier extension for case insensitive search of tokens

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#272]
Is it possible to have an Aidbox modifier extension that allows searching by ignoring the case when searching tokens?

**Comment by yosbeleg89** [comment]
My use case for this is searching by `email` on the ContactPoint, see https://www.hl7.org/fhir/search.html#token

```For tokens, matches are literal (e.g. not based on subsumption or other code system features). Match is case sensitive unless the underlying semantics for the context indicate that the token should be interpreted case-insensitively (see, e.g. CodeSystem.caseSensitive). Note that matches on _id are always case sensitive. If the underlying data type is string then the search is not case sensitive.```

I think that Aidbox could make the search of contact points not case sensitive or maybe provide a way to search case insensitive on them.

**Comment by KGOH** [comment]
This feature currently is not implemented

**Comment by KGOH** [comment]
@yosbeleg89 we won't implement case insensitive token search as specified in fhir doc, but instead in the latest 0.5.0-SNAPSHOT you can use :text modifier to make ilike on the field
For example: `GET /Patient?email:text=gMaiL`
Here's documentation: https://docs.aidbox.app/basic-concepts/search-1#token

**Comment by yosbeleg89** [comment]
Thanks, I wanted to notice that the documentation says:

```
Match is case sensitive unless the underlying semantics for the context indicate that the token should be interpreted case-insensitively
```

I think that telecom is one of those cases. While `:text` helps to search case insensitive way, it also do partial matches, I was looking for an exact match but case insensitive.

**Comment by KGOH** [comment]
Added [:i modifier](https://docs.aidbox.app/basic-concepts/search-1#token) for this use case
