### ISSUE TITLE
ResourceType extra property in json-schema for Elements

### ISSUE THREAD

**Issue by jyeros** [Aidbox/Issues#275]
Aidbox return `resourceType` when call to `json-schema` operation to Elements and not only to Resources, reading here [json-spec-fhir](https://www.hl7.org/fhir/json.html) only [resources](https://www.hl7.org/fhir/resource.html) like `Patient` need to have `resourceType` but not [elements](https://www.hl7.org/fhir/element.html) like `Address`

for example, it is valid in aidbox

```
Put /fhir/Patient/pat11

address:
- resourceType: Address
```

and it should not be

`devbox; 0.4.9; bdf14e28`

**Comment by niquola** [comment]
Thx, fixed in 0.5.0-SNAPSHOT
