### ISSUE TITLE
linkId for Questionnaire.item is optional

### ISSUE THREAD

**Issue by projkov** [Aidbox/Issues#283]
According to the FHIR spec Questionnaire.item.linkId is required string. But in the Aidbox 4.0.0 this attribute is optional.

**Comment by KGOH** [comment]
The reason of this error [is here](https://github.com/HealthSamurai/sansara/blob/190f42bab3557bcb39d40be2feff8091ff85f816/box/import/fhir/import.clj#L365)
@niquola we need your opinion on how to properly fix this

**Comment by ruscoder** [comment]
> The reason of this error [is here](https://github.com/HealthSamurai/sansara/blob/190f42bab3557bcb39d40be2feff8091ff85f816/box/import/fhir/import.clj#L365)
> @niquola we need your opinion on how to properly fix this

Why it was added for linkId only? Is there any issues with having it required? What is the status of this task?

**Comment by Nesmeshnoy** [comment]
Hi @ruscoder, 

How critical is it for you? We're working on zen profiles to solve such types of problems. 

Join the discussion here https://github.com/Aidbox/Issues/discussions

**Comment by ruscoder** [comment]
But it's a bug in general, not only in my case. It allows invalid data to be in the DB. Adding custom profiles won't solve the issues because this property must be required according to spec
