### ISSUE TITLE
Add support for _sort/search by _createdAt (cts)

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#286]

**Comment by ruscoder** [comment]
It can be something like that https://www.hl7.org/fhir/search.html#lastUpdated

**Comment by niquola** [comment]
Do not forget to add documentation for new search parameter!

**Comment by KGOH** [comment]
Added in 0.5.0-SNAPSHOT; f769f4b. Documentation WIP

**Comment by KGOH** [comment]
Documentation: https://app.gitbook.com/@aidbox/s/project/basic-concepts/search-1/_lastupdated

**Comment by KGOH** [comment]
_sort for _createdAt not implemented yet

**Comment by KGOH** [comment]
_sort=_createdAt added in 0.5.0-SNAPSHOT; 8a0bb8c
