### ISSUE TITLE
Include a reference from more than a resourceType works only for last

### ISSUE THREAD

**Issue by jyeros** [Aidbox/Issues#287]
We are trying to include from a references that point to 2 resourceTypes, for example 

`Get /Invoice?_include=subject:Patient,subject:Organization` ❌ 

We want include subject of type Patient and of type Organization but look like aidbox is include only the last one, in this example is only include the ones of type Organization and if we change the order only include the one of types Patient.

The same happen if repeat include parameter instead comma

`Get /Invoice?_include=subject:Patient&_include=subject:Organization` ❌ 

It works if we use `_with` adibox parameter

`Get /Invoice?_with=subject{Patient,Organization}` ✅ 

devbox; 0.5.0-SNAPSHOT; 166e7d9b;

**Comment by KGOH** [comment]
Fixed. 0.5.0-SNAPSHOT; 6ad8f01b
