### ISSUE TITLE
Narrative:xhtml data type should not allow script injection

### ISSUE THREAD

**Issue by orlandow** [Aidbox/Issues#29]
According to https://www.hl7.org/fhir/narrative.html#xhtml

> The contents of the div element are an XHTML fragment that SHALL contain only the basic HTML formatting elements described in chapters 7-11 (except section 4 of chapter 9) and 15 of the HTML 4.0 standard, <a> elements (either name or href), images and internally contained style attributes. The XHTML content SHALL NOT contain a head, a body element, external stylesheet references, deprecated elements, scripts, forms, base/link/xlink, frames, iframes, objects or event related attributes (e.g. onClick). This is to ensure that the content of the narrative is contained within the resource and that there is no active content. Such content would introduce security issues and potentially safety issues with regard to extracting text from the XHTML.

We are rendering resources with that datatype and allowing scripts could cause security issues

**Comment by mlapshin** [comment]
Thanks for reporting this, we can implement some whitelist filtering, I guess, to achieve this. Although I need to discuss it with the team.

As an alternative, you can perform the same HTML filtering operation on your side when creating new resources with narrative content.

**Comment by orlandow** [comment]
Yes, the problem is that we are using a SPA with a token, so any user could create narrative content circumventing the check

**Comment by mlapshin** [comment]
I see

**Comment by orlandow** [comment]
We are now stripping the narrative on rendering using `react-html-parser` but we think aidbox should prevent script injection anyway

**Comment by mlapshin** [comment]
Implemented in `0.3.3-162-g0f862aa`
