### ISSUE TITLE
Resource type missing in AccessPolicy when operation used

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#292]
I'm having an issue with an AccessPolicy when it is used an operation (App).

```
/QuestionnaireResponse/qr1/$someoperation
```

Usually when the operation is not used, the model for the AccessPolicy contains the resource type:

```JSON
"params": {
        "__debug": "policy",
        "resource/type": "QuestionnaireResponse",
        "resource/id": "qr1"
    }
```

But when the operation is used the model does not contains it, making the access policy fail.

**Comment by niquola** [comment]
Use {name: param-name, const: resource-type} in operation definition

**Comment by yosbeleg89** [comment]
It worked 👌 . Thanks
