### ISSUE TITLE
Support to '*' in search including _include and _revinclude

### ISSUE THREAD

**Issue by raydel95** [Aidbox/Issues#30]
When querying resources using query parameters `_include` and `_revinclude` with value `*`, the server response is internal server error
Example:
Using FHIR: 3.3.0
 Aidbox image: 0.3.3-177-g9cedbb7
Request example:
`GET [base]/fhir/Patient?_id=[id]&_include=*`

**Comment by niquola** [comment]
Should work on 0.4.2

**Comment by orlandow** [comment]
It only works for `_include`, `_revinclude` returns the same resources as `_include` 🤔
