### ISSUE TITLE
Error codes at OperationOutcome.issue

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#300]
`OperationOutcome.issue` object needs complete machine-readable problem description. Now it contains field `expression: Resource.path` which serves good as problem source, but details are just human-readable text like this: "Value at resource.field has bad format". Some code (like `bad-format` for the case) would be very useful.

**Comment by KGOH** [comment]
OperationOutcome resource is formed by fhir spec
https://www.hl7.org/fhir/operationoutcome-definitions.html#OperationOutcome.issue.expression
`expression` contains FHIR path expression

**Comment by kzotoff** [comment]
@KGOH path expression only shows **where** incorrect field is located, but nothing about **why** it is incorrect, so the the only machine-friendly knowledge of **why** is response HTTP status.
