### ISSUE TITLE
Possible bug with data cleaning

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#301]
In 0.4.9-RC3 I can not create this resource:
```
target:
- detail: {boolean: true}
subject: {id: test, display: test, resourceType: Patient}
description:
  coding:
  - {}
lifecycleStatus: planned
id: test
resourceType: Goal
```

After 0.4.9 it is possible.

@niquola is it a bug? Please pay attention to an empty object in description.coding.0

PS: devbox 0.4.9-P1

**Comment by niquola** [comment]
Yes we decided for user convenience to allow empty objects and arrays
