### ISSUE TITLE
RxNorm bundle from the docs fails to install

### ISSUE THREAD

**Issue by orlandow** [Aidbox/Issues#304]
Following this tutorial: https://docs.aidbox.app/terminology/terminology-api#rxnorm

Installing RxNorm from this URL: https://storage.googleapis.com/aidbox-public/fhir-terminology/rxnorm-10072019.ndjson.gz

this request:
```
POST /terminology/$import

url: "https://storage.googleapis.com/aidbox-public/fhir-terminology/rxnorm-10072019.ndjson.gz”
```

fails with:
![image](https://user-images.githubusercontent.com/2000738/83543260-276c9d00-a4ca-11ea-86d9-5f3e985d9d1b.png)

**Comment by niquola** [comment]
Try this url - https://storage.googleapis.com/aidbox-public/fhir-terminology/rxnorm-2019.ndjson.gz

**Comment by orlandow** [comment]
Perfect, it works now.
