### ISSUE TITLE
Enable nesting of full referenced resources in _with and _include searches

### ISSUE THREAD

**Issue by joshlabau** [Aidbox/Issues#306]
Currently referenced resources in _with and _include searches come back as siblings. For example:

    GET /Patient?_with=user

    resource:
      resourceType: Patient
      id: <uuid>
    resource:
      resourceType: User
      id: <uuid>
      otherAttributes...
    resource:
      resourceType: User
      id: <uuid>
      otherAttributes...

That means if you get back 10 Patients and 10 Users, you need to iterate through theme to match them up.

This kind of pre-loading would be more like other ORM functionality if it nested the full record of each referenced resource as a child of the root. This would allow much easier iteration without requiring a step to manually bind references to their parents. So for example, the same query above would return:

    GET /Patient?_with=user

    resource:
      resourceType: Patient
      id: <uuid>
      otherAttributes....
      resource:
        resourceType: User
        id: <uuid>
        otherAttributes...
      resource:
        resourceType: User
        id: <uuid>
        otherAttributes...

**Comment by Zallin** [comment]
FHIR spec says that a [Bundle](https://www.hl7.org/fhir/bundle.html) is returned from a search query. We have to support this behaviour to be FHIR compliant.

However, there is a [GraphQL API](https://docs.aidbox.app/api-1/graphql-api) that returns nested resources in ORM-like manner.
