### ISSUE TITLE
Token expiration after N seconds since the last action

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#309]
Using access_token_expiration in the Client allows expiring tokens after N seconds since the issued date. We need to make the token expired after N seconds since the last action.

**Comment by Zallin** [comment]
Why do you consider this behaviour correct? Any use cases?

**Comment by Zallin** [comment]
Looks like this behaviour can cause a security vulnerability when a token does not expire at all.

**Comment by ruscoder** [comment]
Seems it was fixed not so long ago
