### ISSUE TITLE
Tags problem

### ISSUE THREAD

**Issue by arey32** [Aidbox/Issues#31]
devbox:0.3.3
fhir-3.0.1

Andrey, [25.12.18 12:57]
 Создаю diagnostic report в meta хочу создать tag

"resourceType" : "DiagnosticReport",
  "id": "00004",
  "meta": {
     "tag": [
            {
                "system": "http://emportal.ru",
                "code": "rogaikopita"
            }
        ]
      },

ресурс создается, но когда я делаю get

"meta": {
        "lastUpdated": "2018-12-25T09:55:06.861Z",
        "versionId": "43",
        "tag": [
            {
                "system": "https://aidbox.app",
                "code": "created"
            }
        ]
    },

**Comment by Aitem** [comment]
Done in devbox v 0.4.0
