### ISSUE TITLE
Health endpoint not showing aidbox version

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#314]
When requesting the `/health` endpoint the *version* is null:

```
status: pass
description: health of aidbox
version: null
releaseId: null
checks:
  uptime:
  - {componentType: system, observedValue: 1172447, observedUnit: s, status: pass, time: '2020-06-05T00:49:47.983Z'}
  memory:utilization:
  - {componentType: system, status: pass, observedValue: 230, observedUnit: Mb}
  db:responseTime:
  - {status: pass, componentType: database, observedValue: 22, observedUnit: ms}
```

Is it possible to add it?

**Comment by Zallin** [comment]
@rublag what is the current implementation state? Can you provide a screenshot or a description?

**Comment by Zallin** [comment]
@rublag can you confirm that it is working as expected right now?

**Comment by rublag** [comment]
@Zallin, It seems that it was alredy fixed on `:edge` 
![image](https://user-images.githubusercontent.com/2961967/125822976-40bc143b-64e1-47da-9c0d-2081a5cbd5ac.png)
