### ISSUE TITLE
Error in SQL access policy causes errors in the rest of the policies

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#315]
I created an sql access policy that had an extra `)` and was causing an exception when it was evaluated. When making a transaction request, the exception was causing the whole transaction to rollback and denying all the entries in the request because the rest of the policies could not be evaluated. I would hope that an exception in an access policy would not stop the evaluation of the rest of them, I know it works this way usually, this is the first time I see this happening and I think it have to be with the transaction, because if we use `batch` the error in the policy still happens but the rest of the policies are correctly evaluated.

Policy error:
```
      error: |-
        ERROR: syntax error at or near ")"
```

Error in the rest of the policies:
```
ERROR: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by Zallin** [comment]
@yosbeleg89 Hello, you see this error when you POST FHIR transaction bundle, right?

What is the expected behaviour in this case? Why do you think that an exception from an incorrect access policy should be ignored?

**Comment by Zallin** [comment]
@niquola Don't you think that an exception in any access policy should stop further evaluation and return 500 status code and an exception?

**Comment by yosbeleg89** [comment]
>Hello, you see this error when you POST FHIR transaction bundle, right?

right

>What is the expected behaviour in this case? Why do you think that an exception from an incorrect access policy should be ignored?

We have found workarounds for this one, the issue is that we had implemented some AccessPolicy thinking of special kind of requests, then when evaluated against other requests it caused the exception, maybe a solution would be to have a way to add some precondition to the AccessPolicy evaluation, then it would be evaluated if it's met.

**Comment by niquola** [comment]
Fixed in edge
