### ISSUE TITLE
Deny access policies

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#316]
Aidbox policies engine evaluates all the AccessPolicy resources and if one says `true` to a request evaluation then it *allows*. There are cases we have general policies that allow a group of requests, but there are special cases where we would like to deny it if some condition is met. It would be helpful that if instead of adding that condition to the policies that allow, we could create a `deny` AccessPolicy that check that condition and if met, then the engine can stop the policies evaluation and **deny** the request.

**Comment by Zallin** [comment]
@niquola what do you think of access policy "deny" mode? 

I think it is conceptually incorrect for us to implement.

**Comment by niquola** [comment]
I do not like this idea - because it will introduce dependency from the order of policies evaluation
