### ISSUE TITLE
Add query-sql to the response of a request when using compartments

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#319]
Is it possible to add `query-sql` to the response of request to the compartment's API, as in others Aidbox's APIs.

**Comment by Zallin** [comment]
Hello, what is your use case? when do you prefer to use compartments instead of FHIR Search API? How does this issue affect you?

**Comment by yosbeleg89** [comment]
I think you can close this issue, it is already implemented in the latest Aidbox versions.

**Comment by yosbeleg89** [comment]
>Why do you want to use compartments API instead of FHIR Search API?

We heavily use FHIR compartments using FHIR and Aidbox API, we also use custom compartments.
