### ISSUE TITLE
Ambiguous login search

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#320]
When logging user with `/auth/token` method Aidbox looks for username at four fields at `User` resource: `id`, `userName`, `nickName`, `email` as it can be seen in logs:

`devbox 08:11:42 w5 [2ms] select * from "user" where id = ? or lower(resource->>'email') = lower(?) or resource->>'nickName' = ? or resource->>'userName' = ? ["user" "user" "user" "user"]`

So if one `User` has `userName: user` and other `User` has `user: user` then aidbox can select incorrect user to login.

Also, as of version 0.5.0-SNAPSHOT e871cb21, there no field `nickName` at `User` resource.

**Comment by Zallin** [comment]
I believe we do not need the nickName and userName matching logic at all. We will investigate on our end and discuss.

**Comment by niquola** [comment]
I removed nickName. Still not sure about userName. It is good for login - it should be unique and required.
But this is a breaking change :(

@kzotoff which attrs do you use for login?  email?

**Comment by kzotoff** [comment]
We use `userName` and in rare cases `id`
Is it able to make it configurable?

**Comment by niquola** [comment]
Yes, i'm thinking exactly about this!
