### ISSUE TITLE
json/patch 500 exception

### ISSUE THREAD

**Issue by suchimauz** [Aidbox/Issues#322]
Hello, I encountered this error in json / patch: if there is only one operation in the array of operations, the response is returned with the status 500 with exception: 
**`No value supplied for key: {: op "replace",: path "/status",: value "noshow"}`**, 
but the operation itself is executed, in this case the status will change to noshow.

If the exact same operation is added to the array of operations, the response is returned successful without any problems.

thank for attention)

**Comment by suchimauz** [comment]
Addition: this error occurs not for 1 operation, but for an odd count of operations

**Comment by niquola** [comment]
Could not reproduce - can you show the whole request?

**Comment by niquola** [comment]
Please use explicit `Content-Type: application/json-patch+json`
Because we have json-merge as well (https://tools.ietf.org/html/rfc7386) and without content-type aidbox tries to guess the patch method.

**Comment by suchimauz** [comment]
okay, thank you!
