### ISSUE TITLE
Support for ETags in compartments

### ISSUE THREAD

**Issue by leandrowilliam** [Aidbox/Issues#328]
**aidbox version**: `0.5.0-SNAPSHOT`

![image](https://user-images.githubusercontent.com/9604296/88302737-30146f00-ccd4-11ea-8290-0594f50d2f1d.png)

![image](https://user-images.githubusercontent.com/9604296/88302796-46222f80-ccd4-11ea-8b66-5565fc978eb3.png)

**Comment by niquola** [comment]
Hi, can you clarify the problem?

**Comment by leandrowilliam** [comment]
Hi, when we request the resource through the compartment it doesn't have a `versionId` and therefore we can't use **ETags**

**Comment by niquola** [comment]
Oh, got you. Will fix it!

**Comment by leandrowilliam** [comment]
thanks
