### ISSUE TITLE
_include does not include the resource when using iterate

### ISSUE THREAD

**Issue by ivangalbans** [Aidbox/Issues#335]
I’m trying to do a query to get CommunicationRequest and include sender field and when sender is of type PractitionerRole I wanna include practitioner as well.

I think these queries should work:
~~~http
GET /CommunicationRequest?id=someid&_include=sender&_include:iterate=PractitionerRole:practitioner
~~~

~~~http
GET /CommunicationRequest?id=someid&_include=sender&_include=CommunicationRequest:sender:PractitionerRole&_include=PractitionerRole:practitioner
~~~

I need the sender anyway and if it is PractitionerRole include practitioner.

**Comment by ivangalbans** [comment]
👀

**Comment by KGOH** [comment]
@ivangalbans hello. Can you consider using `_with` parameter instead of `_include`?
https://docs.aidbox.app/api-1/fhir-api/search-1/_include-and-_revinclude#using-the-_with-parameter

**Comment by yosbeleg89** [comment]
I think this is already fixed in the recent Aidbox releases.

**Comment by ivangalbans** [comment]
yeah, thanks for testing Yosbel
thanks @KGOH
