### ISSUE TITLE
Wrong response status on http errors

### ISSUE THREAD

**Issue by KGOH** [Aidbox/Issues#338]
If http error arises in transaction bundle response status is 200
![image](https://user-images.githubusercontent.com/11963737/95982146-0e80da80-0e20-11eb-8e79-cdfc528078fa.png)

**Comment by rublag** [comment]
![image](https://user-images.githubusercontent.com/2961967/112967274-c8ac9a00-9153-11eb-81fa-7206f173960e.png)
Can't reproduce; added 500 HTTP error support.
