### ISSUE TITLE
Problems with _include:iterate search parameter

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#34]
As commented in the [original issue](https://github.com/Aidbox/Issues/issues/18#issuecomment-456185827) aidbox is not including the results targeted by the `_include:iterate` search parameter.

Query example:

```
/fhir/DiagnosticReport?_count=10&_totalMethod=count&subject=123&_include=DiagnosticReport:result&_include:iterate=Observation:has-member
```
In this case the Observations targeted by `has-member` search parameter are not included in the reponse.

**Comment by mlapshin** [comment]
fixed in `0.3.3-231-g99fffd6`
