### ISSUE TITLE
DaVinci: Accessing /fhir/Endpoint warning: expected value "application/fhir+json" for 'Content-Type' header in response

### ISSUE THREAD

**Issue by artemt-wa** [Aidbox/Issues#340]
Results [here](https://touchstone.aegis.net/touchstone/scriptexecution?exec=202011030341059275786228&qn=/FHIRSandbox/DaVinci/FHIR4-0-1-Test/PDEX/PlanNet/03-Query/dv-pdex-r4-03-PlanNet-03-Query-01-endpoint-json#WAITING_OPER)

**Comment by Zallin** [comment]
fixed both for :stable and :edge
