### ISSUE TITLE
DaVinci: Support /fhir/List with a profile argument

### ISSUE THREAD

**Issue by artemt-wa** [Aidbox/Issues#341]
[This request](https://vc202011.aidbox.app/fhir/List?_profile=http%3A%2F%2Fhl7.org%2Ffhir%2Fus%2FDavinci-drug-formulary%2FStructureDefinition%2Fusdf-CoveragePlan)
raises an error `{"resourceType":"OperationOutcome","status":422,"issue":[{"severity":"error","code":"invalid","diagnostics":"No search parameter for List.profile"}]}`. 
This error is fatal in DaVinci tests

**Comment by Zallin** [comment]
as of right now this search param is not implemented. Can you confirm that you still need it for DaVinci test?
