### ISSUE TITLE
fhir search: organization.partof does not work in include

### ISSUE THREAD

**Issue by artemt-wa** [Aidbox/Issues#342]
This [request for Location](https://vc202011.aidbox.app/fhir/Location?_include=Location%3ApartOf) and [request for Organization](https://vc202011.aidbox.app/fhir/Organization?_include=Organization%3ApartOf) 
both return `Could not resolve parameter Location.partOf`

**Comment by Zallin** [comment]
fhir/Organization?_include=Organization%3ApartOf

returns 

{"resourceType":"OperationOutcome","status":422,"issue":[{"severity":"error","code":"invalid","diagnostics":"Could not resolve parameter Organization.partOf"}]}

**Comment by Zallin** [comment]
@artemt-wa you have to use fhir/Organization?_include=Organization%3Apartof (partof is in lowercase instead of partOf)

https://www.hl7.org/fhir/organization.html#search
