### ISSUE TITLE
As a user I cannot create new Resources in JSON using smart Aidbox UI without refreshing (F5) a 'new resource' page

### ISSUE THREAD

**Issue by artemt-wa** [Aidbox/Issues#343]
Severity: cosmetic.
Browser: Firefox
Steps to reproduce:
- visit https://vc202011.aidbox.app/static/console.html#/entities/DeviceRequest/new
- (failed) click on JSON button . URL changed to "https://vc202011.aidbox.app/static/console.html#/entities/DeviceRequest/new?_view=json" , but redirect/reload is not happened
- refresh the page with a "?_view=json" argument
- (workaround succeeded) the format switched to JSON

**Comment by Zallin** [comment]
the issue is confirmed, will be fixed soon
