### ISSUE TITLE
Cache client on app

### ISSUE THREAD

**Issue by Aitem** [Aidbox/Issues#347]
Add caching client on App layer 

![Screenshot 2020-11-09 at 16 15 12](https://user-images.githubusercontent.com/1309701/98545602-c92cbd00-22a6-11eb-8114-a8491b41a896.png)

**Comment by Zallin** [comment]
probably Client resource can be marked as Meta and used in aidbox cache..

**Comment by Zallin** [comment]
we also need to understand from where we query the Client resource frequently
