### ISSUE TITLE
?| operator doesn't work in DB Console

### ISSUE THREAD

**Issue by vganshin** [Aidbox/Issues#358]
Try run it in db console.

```sql
select '["Category A", "Category D"]'::jsonb ?| array['Category A', 'Category B'];
```

btw, I found it here: https://stackoverflow.com/questions/32812526/postgresql-json-array-intersection-query

**Comment by vganshin** [comment]
Скорее всего причина в том, что `?` в jdbc — это литерал для подстановки параметров. Возможно его можно экранировать.

**Comment by KGOH** [comment]
> Возможно его можно экранировать.
@vganshin, верно. Экранируется он вторым `?`:
`select '["Category A", "Category D"]'::jsonb ??| array['Category A', 'Category B'];`
