### ISSUE TITLE
Url encoding problems when working with iterate

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#36]
When working with `:iterate` if the querystring is encoded then the request fails. For example:

GET -> `/fhir/Practitioner?_revinclude=PractitionerRole%3Apractitioner&identifier=http%3A%2F%2Fsomesystem|somevalue&_include%3Aiterate=PractitionerRole%3Aorganization`
Returns 500 as status code and error message: `No search parameter for Practitioner.include%3Aiterate\"`

But if just change the encoding of the `:` before the `iterate` then it works:
GET -> `/fhir/Practitioner?_revinclude=PractitionerRole%3Apractitioner&identifier=http%3A%2F%2Fsomesystem|somevalue&_include:iterate=PractitionerRole%3Aorganization`

**Comment by mlapshin** [comment]
fixed in 0.3.3-240-g555a6f0
