### ISSUE TITLE
Add $loggy operation

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#361]
Add API endpoint that accepts any JSON and write it to aidbox log including elastic search log backend.

**Comment by KGOH** [comment]
https://docs.aidbox.app/advanced/reactive-api-and-subscriptions/usdsnapshot-usdwatch-and-usdversions-api#query-string-parameters

**Comment by KGOH** [comment]
https://docs.aidbox.app/administration/receive-logs-from-your-app
