### ISSUE TITLE
Unable to create or connect to a database if DB name or rolename contains hyphens or hostname

### ISSUE THREAD

**Issue by eserdk** [Aidbox/Issues#362]
Several exceptional cases:

1. Cloud-hosted database with username of the following format `user-name@some-azure-host` results into the following:
```
Start Aidbox.Dev
Logging to STDOUT pretty
09:41:38 main [83ms] SELECT 1 
09:41:38 main [252ms] select pg_advisory_lock(7777) 
09:41:39 main [138ms] SELECT TRUE FROM "pg_catalog"."pg_roles" WHERE "rolname" = ? ["user-name@some-azure-host"]
09:41:39 :error main [31ms] :db/ex-error {:d 31, :sql "CREATE USER user-name@some-azure-host WITH ENCRYPTED PASSWORD 'somepassword'"}
Execution error (PSQLException) at org.postgresql.core.v3.QueryExecutorImpl/receiveErrorResponse (QueryExecutorImpl.java:2440).
ERROR: syntax error at or near "-"
```
**NOTE:** this role (`user-name` - without hostname) already exists in the database, but aidbox still tries to create it.

2. If I remove the hostname in the username, resulting logs look like this:
```
Error while connecting to {:host "some-azure-host.postgres.database.azure.com", :port "5432", :user "user-name", :database "postgres"} - FATAL: Invalid Username specified. Please check the Username and retry connection. The Username should be in <username@hostname> format.
Retry connection to  {:host some-azure-host.postgres.database.azure.com, :port 5432, :user user-name, :database postgres}
```
**NOTE:** `postgres` is passed as a database for unknown reason, although `some-database` was specified.

3. Database containing hyphen in its name cannot be created, see **1** for example - it behaves in the same way.

**Conclusion:** hyphens and `@` are not supported and are incorrectly parsed and passed. Odd default variables instantiation. 

If it's not a bug, but just my misunderstanding and my fault, please, correct me.

**Comment by Zallin** [comment]
Hello @eserdk, do you use azure postgres with aidbox?

Have you tried our custom postgres image healthsamurai/aidboxdb:13.2? It should support your use case. Can you try it out?

**Comment by eserdk** [comment]
Hello @Zallin, sorry for the delayed response. 

Yes, we use azure postgres instance. We're not allowed to use any other database, neither in cluster, nor deployed externally, as per non-functional requirement. As far as I remember, `healthsamurai/aidboxdb` worked pretty well when I tried it locally.
