### ISSUE TITLE
SearchQuery: fix revinclude for array references

### ISSUE THREAD

**Issue by Zallin** [Aidbox/Issues#365]
```
"includes": {
    "appointment": {
        "path": [
            "basedOn"
        ],
        "reverse": true,
        "resource": {
            "id": "Appointment",
            "resourceType": "Entity"
        }
    }
}

```
SELECT subj.* FROM "appointment" subj
WHERE /* ids */ (knife_extract_text(resource, $$[["basedOn",{"resourceType":"ServiceRequest"},"id"]]$$))[1]
IN (?,?,?) LIMIT 1000 ["c3a1c736-12a0-461e-a665-8e672c5f3a20" "8f111ffb-12fd-42b7-bf34-5f3f79129577"]

When you query Appointment and try to revinclude ServiceRequest on basedOn property incorrect SQL is generated. It should use postgres @> to match ids from basedOn references array.

**Comment by KGOH** [comment]
Maybe you meant to say 
"When you query ServiceRequest and try to revinclude Appointment on basedOn property incorrect SQL is generated. It should use postgres @> to match ids from basedOn references array."
?
