### ISSUE TITLE
Unwanted property created when used Aidbox references in FHIR API

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#37]
If we by mistake make a PUT to `/fhir` using Aidbox references then it is adding an `_id` property:

```
PUT -> /fhir/PractitionerRole/role1
----------------------------------------
id: role1
resourceType: PractitionerRole
practitioner:
  resourceType: Practitioner
  id: pract1
organization:
  resourceType: Organization
  id: fl
-----------------------------------------
Response:
{
    "id": "role1",
    "meta": {
        "lastUpdated": "2019-02-06T17:18:49.196Z",
        "versionId": "286"
    },
    "organization": {
        "_id": "fl",
        "reference": "Organization/fl",
        "id": "fl"
    },
    "practitioner": {
        "_id": "pract1",
        "reference": "Practitioner/pract1",
        "id": "pract1"
    },
    "resourceType": "PractitionerRole"
}
```

It would be better if an error is returned rather than creating the `_id` property.

**Comment by niquola** [comment]
Sadly this is a name clash we could not resolve, because id attribute is valid in FHIR in any place - xml atavism

**Comment by yosbeleg89** [comment]
🤔 even in [References](https://www.hl7.org/fhir/references.html#Reference)?

**Comment by niquola** [comment]
Anywhere :(

**Comment by yosbeleg89** [comment]
Yep, you are right, it is in Element, but anyway I think the `_id` should not be generated.

**Comment by niquola** [comment]
We generate it to store original id in an element. I do not see an elegant solution for this - so i'm closing it.

**Comment by yosbeleg89** [comment]
@niquola about this issue, we opened an issue on **fhir-net-api** `https://github.com/FirelyTeam/fhir-net-api/issues/960`, but it seems that in FHIR Json format http://hl7.org/fhir/json.html#primitive elements stating with `_` have a special meaning.
