### ISSUE TITLE
Missing Attribute.isRequired for required polymorphic FHIR resources

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#380]
For example, https://www.hl7.org/fhir/questionnaire.html Questionnaire.item.answerOption.value is required (1..1). 

But `get /Attribute/Questionnaire.item.answerOption.value` - isRequired is missing.

It affects all required polymorphic attributes in FHIR resources

**Comment by Zallin** [comment]
We think that it is related to FHIR -> Aidbox meta conversion, marking as low priority for now

**Comment by ruscoder** [comment]
Still an issue

**Comment by KGOH** [comment]
I confirm that requires for all polymorphic values are missing. This is a breaking change

In [zen profiles](https://docs.aidbox.app/profiling-and-validation/profiling-with-zen-lang) there's no such issue

How critical is this problem for you, @ruscoder?
