### ISSUE TITLE
ERROR: for devbox-db  Cannot create container for service devbox-db

### ISSUE THREAD

**Issue by dagagf** [Aidbox/Issues#381]
Hi! I tried to install devbox on my personal computer. After following each steps, I ran "docker-compose up -d" and got an error. Here's the message:

![image](https://user-images.githubusercontent.com/47257138/117866865-9f5c4f00-b265-11eb-8bf6-57591bf4d9c2.png)

I can't seem to figure out what I did wrong.
Please send help.

**Comment by Zallin** [comment]
@dagagf Hello, what OS and docker version are you running? Which healthsamurai/aidboxdb image are you using?
