### ISSUE TITLE
AccessPolicy.engine breaks everything if omitted [BUG]

### ISSUE THREAD

**Issue by Nesmeshnoy** [Aidbox/Issues#384]
**Describe the bug**

I was able to create AccessPolicy without engine defined and I was after unable to access anything because it says that the created rule didn't have an engine specified

**Steps to reproduce the behavior**
1. Create blank AccessPolicy without .engine
2. Make any API call
3. Receive 500 error from the server

**Expected behavior**

Aidbox shouldn't allow create AccessPolicy without .engine attr.

**Versions:**
 - Aidbox image version

 - [ ] stable
 - [X] edge
 - [ ] timestamped image (please provide the exact name)

**Comment by Zallin** [comment]
the bug is reproduced, looking forward to fixing it

**Comment by Zallin** [comment]
- [ ] we need to mark AccessPolicy.engine with isRequired
- [ ] make sure to add .engine to the policies that are created by default by Aidbox
- [ ] handle missing engine correctly by implementing the default multimethod
