### ISSUE TITLE
aidboxdb: install pgagent by default

### ISSUE THREAD

**Issue by Zallin** [Aidbox/Issues#386]
**Is your feature request related to a problem? Please describe.**

One of the approaches to build analytics on top of Aidbox that stores large amounts of data is to implement an ETL process that flattens the data to the tabular format from the jsonb. BI vendors like Tableau, PowerBI, etc provide better support for tabular than for jsonb. Also, the performance might be better on tabular, and indexing is more straightforward.

**Describe the solution you'd like**

To support this use case we want to install pgagent by default into aidboxdb. Using its scheduling capabilities an ETL process implementation using tables/materialized views and stored procedures is possible.

**Describe alternatives you've considered**

An alternatives are the following:
- to rely heavily on postgres jsonb indexing capabilities and scale postgres vertically to make the queries performant
- to use a scheduling tool external to postgres

**Additional context**

**Comment by jewilkinson** [comment]
This is Jesse with VITL - I have subscribed for updates.  Thank you for looking into this.

**Comment by jewilkinson** [comment]
This is Jesse - I have subscribed for updates.

**Comment by Nesmeshnoy** [comment]
https://docs.aidbox.app/getting-started/installation/aidboxdb-image
