### ISSUE TITLE
[BUG] POST /fhir/App doesn't trigger Operation/create-app

### ISSUE THREAD

**Issue by KGOH** [Aidbox/Issues#387]
**Describe the bug**

POST /fhir/App doesn't trigger Operation/create-app

**Steps to reproduce the behavior:**

Walk through [this doc](https://docs.aidbox.app/app-development-guides/tutorials/sdc-with-custom-resources), but post the App to `/fhir/App`, the Entity/Vitals wouldn't be created

**Expected behavior**

Post to /fhir/App should trigger Operation/create-app

**Comment by Zallin** [comment]
the following implementation options are possible

- [ ] Post to /fhir/App should trigger Operation/create-app and trigger the resources conversion
- [ ] Forbid this API call at all

**Comment by KGOH** [comment]
Fixed on edge 60d1571a. App API calls with /fhir prefix are now forbidden
