### ISSUE TITLE
Confusing interpolation in SQL AccessPolicy

### ISSUE THREAD

**Issue by mlapshin** [Aidbox/Issues#39]
When one writes SQL policy he expects that arrays will be interpolated in the SQL statement as JSONB value. However, they are interpolated as Postgres arrays (i.e. `{foo,bar}` for array of strings). We need to review how request data is being interpolated into the statement values.

**Comment by niquola** [comment]
agree, let's do all composites as jsonb - or at least document interpolation rules

**Comment by mlapshin** [comment]
Now both arrays and objects are interpolated as JSONB values:

```
select {{user}}->>'id';

select {{array}}->>0;
```
