### ISSUE TITLE
Incorrect handler called twice

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#391]
If endpoint handler returns, for example, JSON, I got the following message: `RuntimeError: Web-handler should return a response instance`. The problem is that the first time endpoint handler is being executed twice.

How to reproduce:
1) Aidbox Python SDK 837127c
2) Minimal app:

```
import logging
from aidbox_python_sdk.main import create_app as _create_app
from aidbox_python_sdk.sdk import SDK
from aidbox_python_sdk.settings import Settings

settings = Settings(**{})
sdk = SDK(settings)

async def create_app():
    app = await _create_app(settings, sdk, debug=True)
    return app

@sdk.operation(methods=['POST'], path=['test'])
async def api_request_test(_, request):
    logging.getLogger().warning('--- WARNING ---')
    return {"result": "ok"}
```
3) Do `POST /test` request

Now comes log:
```
devbox_1     | devbox 06:00:10 w2 POST /test
devbox_1     | devbox 06:00:10 w2 policy devbox-policy
devbox_1     | devbox 06:00:10 w2 [1ms] 
backend_1    | --- WARNING ---
backend_1    | Unhandled runtime exception
backend_1    | Traceback (most recent call last):
backend_1    |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 447, in start
backend_1    |     raise RuntimeError("Web-handler should return "
backend_1    | RuntimeError: Web-handler should return a response instance, got {'result': 'ok'}
backend_1    | 
backend_1    | --- WARNING ---
backend_1    | Unhandled runtime exception
backend_1    | Traceback (most recent call last):
backend_1    |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 447, in start
backend_1    |     raise RuntimeError("Web-handler should return "
backend_1    | RuntimeError: Web-handler should return a response instance, got {'result': 'ok'}
backend_1    | 
```

This occurs only once after start. All other calls causes handler to be executed only once, as expected.

**Comment by ruscoder** [comment]
Hi @kzotoff!

BTW, here is a separate repository for python SDK - https://github.com/Aidbox/aidbox-python-sdk

Why you need to return plain JSON without a special wrapper? Python SDK uses aiohttp lib for representing operation handlers, and you have to return your JSON with `web.json_response` wrapper, see [aiohttp doc](https://docs.aiohttp.org/en/stable/web_reference.html#json-response) for details.

Example:
```
from aiohttp import web
...

@sdk.operation(methods=['POST'], path=['test'])
async def api_request_test(_, request):
    logging.getLogger().warning('--- WARNING ---')
    return web.json_response({"result": "ok"})
```

**Comment by kzotoff** [comment]
@ruscoder The meaning of the issue is that handler is being called **twice**. Can I be sure that will not occur at some correct situation?

**Comment by ruscoder** [comment]
@kzotoff Never seen this behavior in our projects. Have you tested it with correct example (with json_response wrapper)?

**Comment by kzotoff** [comment]
@ruscoder With correct response it works as expected

**Comment by ruscoder** [comment]
@kzotoff cool. So, this isn't an issue anymore and we can close it?

**Comment by kzotoff** [comment]
@ruscoder it can be annoying. In my case I created very complex endpoint and missed that wrapper in one condition. Also business-logic at the endpoint was such that second try with same parameters should return an error. So spent some hours searching tons of logs why my Slot resources are already busy.

**Comment by Zallin** [comment]
@ruscoder can we investigate this a bit more? Is it the expected behaviour that the handler is called twice?

**Comment by niquola** [comment]
Can it be fixed in python SDK, @ruscoder?
