### ISSUE TITLE
Aidbox docker: performance issues on M1 processors

### ISSUE THREAD

**Issue by Zallin** [Aidbox/Issues#393]
**Describe the bug**

aidboxdb and aidbox docker images have bad performance on the latest m1 processors. For now we only know of the local development use case, but other may follow in future.

**Urgency**
- [ ] minor
- [x] medium
- [ ] major
- [ ] critical
- [ ] show-stopper

**Comment by Zallin** [comment]
for now we decided to proceed with static builds of stable and aidboxdb for ARM architecture. WIP by @ir4y

**Comment by ruscoder** [comment]
The issue becomes more and more actual because of the wide spreading of M1 among developers.

Any updates?

**Comment by Nesmeshnoy** [comment]
Added Devbox and Aidboxdb multi-arch Images (ARM64 and AMD64)
https://hub.docker.com/r/healthsamurai/devbox/tags
https://hub.docker.com/r/healthsamurai/aidboxdb/tags
