### ISSUE TITLE
[BUG] datadog exporter: incorrect fallback to stdout

### ISSUE THREAD

**Issue by Zallin** [Aidbox/Issues#395]
As a user I configure datadog exporter with environment variable AIDBOX_DD_API_KEY, but logs are not shown in Datadog and I get the following in the stdout
```
clojure.lang.LazySeq@25efeea
clojure.lang.LazySeq@8298b60f
clojure.lang.LazySeq@91efd99
clojure.lang.LazySeq@5151ad06
clojure.lang.LazySeq@f5b898f8
clojure.lang.LazySeq@ffccb899
clojure.lang.LazySeq@91694eed
clojure.lang.LazySeq@d64453dc
clojure.lang.LazySeq@f0d81511
clojure.lang.LazySeq@588c2891
clojure.lang.LazySeq@aa714665
clojure.lang.LazySeq@e2516f61
clojure.lang.LazySeq@25bb27e8
clojure.lang.LazySeq@5c880cd6
clojure.lang.LazySeq@1d1761a8
clojure.lang.LazySeq@dd879d1b
clojure.lang.LazySeq@9d24a54b
```
**Urgency**
- [ ] minor
- [x] medium
- [ ] major
- [ ] critical
- [ ] show-stopper

**Steps to reproduce the behavior:**

1. Provide an incorrect AIDBOX_DD_API_KEY environment variable, do not provide file fallback variable
2. Set the log batch size to 1 (optional)
3. Wait until you see lazyseq prints in stdout

**Expected behavior**

I expect logs to be shown correctly in json format

**Versions:**

 - Aidbox image version
   - [ ] stable
   - [x] edge
   - [ ] timestamped image (please provide the exact name)

**Comment by Zallin** [comment]
for transparency we need to add an error print if the datadog service is unavailable

**Comment by berryvanesch** [comment]
We have this issue, we have a Azure Postgressql db flexibal server and a Azure container instance with a aidbox edge container running on it.
