### ISSUE TITLE
History for $load and $import

### ISSUE THREAD

**Issue by tklee** [Aidbox/Issues#417]
## I need the following improvement
History for resources affected by $load or $import

## The expected benefit
We are going to use bulk import on a nightly basis and need to have a source of truth for the history of every resource instance as it evolves

## Additional context
As discussed in Zoom chat 8/17/2021 with Project Ronin

**Comment by niquola** [comment]
We added `update: true` flag to $load operation - https://docs.aidbox.app/api-1/bulk-api-1/usdload#update-true

**Comment by tklee** [comment]
thanks @niquola that was fast!

**Comment by Nesmeshnoy** [comment]
@tklee please check update: true
https://docs.aidbox.app/api-1/bulk-api-1/usdimport-and-fhir-usdimport
https://docs.aidbox.app/api-1/bulk-api-1/usdload
