### ISSUE TITLE
Display user roles in __debug=policy

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#418]
## Problem I need to solve
It will improve debugging experience

## Solution I see
Display role array along with user/client.

**Comment by Nesmeshnoy** [comment]
@ruscoder do you mean Role resource or something else?

**Comment by ruscoder** [comment]
Yes, it's about Role resource.

**Comment by ruscoder** [comment]
Just want to add few details. If User has some Role related resources, one policy in that case will be evaluated for every Role.

And now __debug=policy shows:
```json
 "policies": [
  {
   "eval-result": false,
   "errors": [
    {
   ...
    }
   ],
   "id": "patient",
   "policy-id": "patient"
  },
  {
   "eval-result": false,
   "errors": [
   ...
    }
   ],
   "id": "patient",
   "policy-id": "patient"
  },
]
``` 

And it's absolutely impossible to understand for what Role resource the policy was evaluated. My suggestion is to add `role` for each policy.

Expected:
```json
 "policies": [
  {
   "eval-result": false,
   "errors": [
    {
   ...
    }
   ],
   "id": "patient",
   "policy-id": "patient",
   "role": {
        "id": "role-1",
         ...role info
    }
  },
  {
   "eval-result": false,
   "errors": [
   ...
    }
   ],
   "id": "patient",
   "policy-id": "patient",
   "role": {
        "id": "role-2",
         ...role info
    }
  },
]
```

**Comment by Nesmeshnoy** [comment]
@ruscoder please check it and let us know if it works as expected
