### ISSUE TITLE
POST to _search API with YAML content type is not working

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#42]
When a POST to the `_search` API is made with `x-www-form-urlencoded` it is working fine, but when using `text/yaml` as content type it is not, for example:

```
POST -> /Patient?_search
Content-Type: text/yaml

gender: male
```
Response:
```JSON
{
    "resourceType": "Bundle",
    "type": "searchset",
    "params": [
        {
            "error": "_search",
            "message": "Do know how to parse: _search"
        }
    ],
    "query-sql": [
        "SELECT \"patient\".* FROM \"patient\" LIMIT ? OFFSET ?",
        100,
        0
    ],
...
```

**Comment by mlapshin** [comment]
fixed in `0.3.3-245-g84834dc`, but JFYI according to the spec `application/x-www-form-urlencoded` is the only acceptable format for POST search requests: https://www.hl7.org/fhir/search.html#Introduction
