### ISSUE TITLE
[BUG] The _format parameter is not supported

### ISSUE THREAD

**Issue by Soyoung7533** [Aidbox/Issues#425]
**Describe the bug**
The response contains an incorrect "Content-Type" header when __format_ query parameter is used. The __format_ parameter should override the HTTP Header Accept.

Please refer https://www.hl7.org/fhir/http.html#parameters.

**Severity**
S2  - Touchstone Conformance Standard Server test suite

**Steps to reproduce the behavior:**
1. Patient read operation with HTTP Header Accept set to XML format and the __format_ request URL parameter set to JSON.

Test the read operation with HTTP Header Accept set to XML format and the __format_ request URL parameter set to JSON. The expected response content is the found Patient resource in JSON format as the __format_ parameter overrides the HTTP Header Accept.

Request:	GET /Patient/9d2f91cd-fe19-a36e-e38d-1db3052aee5e?_format=application%2Ffhir%2Bjson
Headers:	
    Accept	 application/fhir+xml;charset=UTF-8

Response:	
Headers:	
    Content-Type	application/json

Failed : The actual value "application/json" did not contain the expected value "application/fhir+json" for 'Content-Type' header in response.
Description:	Confirm that the returned HTTP Header Content-Type contains the FHIR mime-type 'application/fhir+json'.

2. Patient read operation with HTTP Header Accept set to XML format and the __format_ request URL parameter set to JSON.

Test the read operation with HTTP Header Accept set to XML format and the __format_ request URL parameter set to JSON. The expected response content is the found Patient resource in JSON format as the __format_ parameter overrides the HTTP Header Accept.

Request:	GET /Patient/9d2f91cd-fe19-a36e-e38d-1db3052aee5e?_format=application%2Ffhir%2Bjson
Headers:	
    Accept		application/fhir+xml;charset=UTF-8

Response:	
Headers:	
    Content-Type	application/json

Failed : 	The actual value "application/json" did not contain the expected value "application/fhir+json" for 'Content-Type' header in response.
Description:	Confirm that the returned HTTP Header Content-Type contains the FHIR mime-type 'application/fhir+json'.

3. Patient read operation with HTTP Header Accept set to XML format and the __format_ request URL parameter set to XML.

Test the read operation with HTTP Header Accept set to JSON format and the __format_ request URL parameter set to XML. The expected response content is the found Patient resource in XML format as the __format_ parameter overrides the HTTP Header Accept.

Request:	 GET /Patient/9d2f91cd-fe19-a36e-e38d-1db3052aee5e?_format=application%2Ffhir%2Bxml
Headers:	
  Accept		application/fhir+json;charset=UTF-8

Response:	
Headers:	
  Content-Type	application/fhir+xml

Failed : 	The actual value "application/fhir+xml" did not contain the expected value "charset=utf-8" for 'Content-Type' header in response.
Description:	Confirm that the returned HTTP Header Content-Type contains 'charset=utf-8' (case-insensitive).

**Expected behavior**
The __format_ parameter should override the HTTP Header Accept.

**Screenshots**

**Versions:**
- OS version

- Docker version (if applicable)

 - Aidbox image version
Stable

 - Aidboxdb version (if applicable)

 - Browser version (if applicable)

 - Cloud provider (if applicable)

**Additional context**
Touchstone Conformance Test

**Comment by niquola** [comment]
Aidbox supports: json, yaml, transit and edn - but no XML
This test is incorrect because it switches between json and "supported" XML. For example, for json and yaml this will work.
