### ISSUE TITLE
[BUG] The Patient create operation fails with XML body when the ‘Content-Type’ header is set

### ISSUE THREAD

**Issue by Soyoung7533** [Aidbox/Issues#427]
**Describe the bug**
The Patient create (via POST) and update (via PUT) operation fail with XML body when the ‘Content-Type’ header is set to 
- application/fhir+xml;charset=UTF-8
- application/fhir+xml
- application/xml

The operation is succeeded when the ‘Content-Type’ header is not set. 
The Pateint create with JSON body works.

**Severity**
S2 - Touchstone Conformance Standard Server test suite

**Steps to reproduce the behavior:**
1. Operation  Create Patient
Description - Test the create operation with HTTP Header Accept and Content-Type set to XML format and no request URL parameters defined. 

 Request:  POST /fhir/Patient
 Headers:
      Accept   application/fhir+xml;charset=UTF-8
      Content-Type  application/fhir+xml;charset=UTF-8

Content:
```
patient resource in xml 
```

Actual Response:
  Status:   422 Unprocessable Entity
  Content:
```
<?xml version="1.0" encoding="UTF-8"?>
<a:OperationOutcome xmlns:a="http://hl7.org/fhir">
    <a:no-attrs-for/>{:type "\"OperationOutcome\""}{:resourceType "OperationOutcome", :text {:status "generated", :div "Invalid resource"}, :issue [{:severity "fatal", :code "invalid", :expression ["Patient.meta.security"], :diagnostics "expected array"} {:severity "fatal", :code "invalid", :expression ["Patient.name"], :diagnostics "expected array"} {:severity "fatal", :code "invalid", :expression ["Patient.deceased.boolean"], :diagnostics "expected boolean"} {:severity "fatal", :code "invalid", :expression ["Patient.active"], :diagnostics "expected boolean"} {:severity "fatal", :code "invalid", :expression ["Patient.identifier"], :diagnostics "expected array"} {:severity "fatal", :code "invalid", :expression ["Patient.telecom"], :diagnostics "expected array"}]}
</a:OperationOutcome>
```
Failed: The actual value "422" did not match the expected value "201" for the response code in response.

2. Operation  Create Patient with ID
Description - Test the update operation with XML content where the resource instance does not exist. The expected response is 201 (Created) and the content is the created Patient resource in XML format.

 Request:  PUT /fhir/Patient/{id}
 Headers:
      Accept   application/fhir+xml;charset=UTF-8
      Content-Type  application/fhir+xml;charset=UTF-8

Content:
```
patient resource in xml 
```
Actual Response:
  Status:   422 Unprocessable Entity

**Expected behavior**
The expected response content is the created Patient resource in XML format. Confirm that the returned HTTP status is 201(Created).

**Screenshots**

**Versions:**
- OS version

- Docker version (if applicable)

 - Aidbox image version
Stable

 - Aidboxdb version (if applicable)

 - Browser version (if applicable)

 - Cloud provider (if applicable)

**Additional context**
Touchstone Conformance Test

**Comment by niquola** [comment]
Aidbox does not support xml.
XML is recommended but not required by FHIR, us-core, Carin

* https://www.hl7.org/fhir/us/core/CapabilityStatement-us-core-server.html#title
* https://build.fhir.org/ig/HL7/carin-bb/CapabilityStatement-c4bb.html#behavior
