### ISSUE TITLE
[BUG] Extension.url is not an absolute URL

### ISSUE THREAD

**Issue by Soyoung7533** [Aidbox/Issues#432]
**Describe the bug**

**Severity**
S0 - Many tests in the Touchstone Conformance Provider Directory API test suite (FHIR4-0-1-PAA-PROVIDER-DIRECTORY-Server) fail due to this issue

**Steps to reproduce the behavior:**
Request: GET /fhir/Endpoint

The content of search request response is a bundle type that includes Bundle.entry[0].resource.ofType(Endpoint).meta.extension[0]. like the following example

```
"meta": {
       "extension": [
        {
              "url": "ex:createdAt",
              "valueInstant": "2021-08-24T09:09:55.104263Z"
          }
        ],
.......
```
Also, Bundle.entry[0].resource.ofType(Endpoint).extension.extension[0]
```

"extension": [
                    {
                        "url": "http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/endpoint-usecase",
                        "extension": [
                            {
                                "url": "type",
                                "valueCodeableConcept": {
                                    "coding": [
                                        {
                                            "code": "HOPERAT",
                                            "system": "http://terminology.hl7.org/CodeSystem/v3-ActReason"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                ]
```

**Expected behavior**
Extension.url is an absolute URL

**Screenshots**
<img width="1049" alt="meta extension url" src="https://user-images.githubusercontent.com/89491379/132602975-abb18097-df09-4f68-8e7b-9712f1e3cf8d.png">
<img width="1046" alt="extension extension url" src="https://user-images.githubusercontent.com/89491379/132602985-71c66c83-117e-4a11-91cf-3da0ec8d2bb7.png">

**Versions:**

 - Aidbox image version
 

 - Aidboxdb version 
 Stable

 - Browser version (if applicable)

 - Cloud provider (if applicable)

**Additional context**
Touchstone Conformance Test

**Comment by KGOH** [comment]
We will provide a configuration of `createdAt` extension url, so it can be set to be an absolute URL

As for the second part with `, Bundle.entry[0].resource.ofType(Endpoint).extension.extension[0]`, this contradicts FHIR spec:

> The url SHALL be a URL, not a URN (e.g. not an OID or a UUID), and it SHALL be the canonical URL of a StructureDefinition that defines the extension. **Except for child extensions defined within complex extensions**, the URL SHALL be an absolute URL.

`Endpoint.extension.extension[0]` is a child extension and `type` is a valid value

**Comment by ddegr** [comment]
Added [`AIDBOX_CREATED_AT_URL`](https://docs.aidbox.app/getting-started/installation/use-devbox-aidbox#optional-environment-variables) environment variable
