### ISSUE TITLE
[BUG] Internal server error (500) response for invalid parameter error

### ISSUE THREAD

**Issue by Soyoung7533** [Aidbox/Issues#435]
**Describe the bug**
Internal server error response returns for a request which includes an invalid parameter

**Severity**
S1

**Steps to reproduce the behavior:**
Request: GET /fhir/HealthcareService?_lastUpdated=badValue

**Expected behavior**
The returned HTTP status is 400 for an invalid parameter.

**Screenshots**
<img width="1099" alt="internal server error" src="https://user-images.githubusercontent.com/89491379/134103251-df39ee64-91f5-4947-8800-eaa68c2d62a3.png">

<img width="1298" alt="Touchstone Invalid parameters test" src="https://user-images.githubusercontent.com/89491379/134103556-e1c0baf3-a3c2-47b0-a6a7-18d7be8418ca.png">

**Versions:**
- OS version

- Docker version (if applicable)

 - Aidbox image version
stable / edge

 - Aidboxdb version (if applicable)

 - Browser version (if applicable)

 - Cloud provider (if applicable)

**Additional context**
Touchstone Conformance Test - /FHIR4-0-1-ProviderDir/DaVinci-PDEX-PlanNet/01-Error-Codes/01-Invalid-Parameters-json

**Comment by Nesmeshnoy** [comment]
@Soyoung7533 looks like it can also be 5xx

> If the search fails (cannot be executed, not that there are no matches), the return value return value SHALL be a status code 4xx or 5xx with an OperationOutcome.

http://hl7.org/fhir/http.html#search

**Comment by Soyoung7533** [comment]
I will check it with Touchstone/Drummond. Thanks.

**Comment by Soyoung7533** [comment]
We had a meeting with Touchstone / Drummond and they are going to review it. They created the test based on the common HTTP Status codes returned on FHIR-related errors  in https://www.hl7.org/fhir/http.html#search

`400 Bad Request - search could not be processed or failed basic FHIR validation rules`

I think that 400 is preferable so that a client app can detect the parameter issue easily based on the HTTP status code. Could you please consider to fix it?

**Comment by rublag** [comment]
Fixed.
