### ISSUE TITLE
[BUG] List of attributes is limited to 100 on Entity Structure page in Aidbox Console

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#439]
Steps to reproduce:
1. open Entity in Aidbox Console
2. Search for Questionnaire
3. Click structure (URL console.html?#/entities/Attribute?entity=Questionnaire)
4. Not all attrs are displayed, because there are more than 100 attrs. It leads to some misunderstandings

**Comment by Nesmeshnoy** [comment]
@ruscoder what Aidbox version do you use? We could not reproduce it on latest versions.

**Comment by ruscoder** [comment]
@Nesmeshnoy Seems it is fixed on the latest version. I tried it on the cloud version, and now the default limit is increased up to 300.
