### ISSUE TITLE
[BUG] Missing ctx parameter on w/resp log message on transaction

### ISSUE THREAD

**Issue by Aitem** [Aidbox/Issues#442]
**Describe the bug**
Missing ctx parameter on w/resp log message on transaction requst

**Severity**
POST /

resourceType: Bundle
type: transaction

**Screenshots**
![Screen Shot 2021-11-10 at 11 24 22](https://user-images.githubusercontent.com/1309701/141143013-b51967e3-2ef5-4a90-8555-da2cc40575c2.png)

**Versions:**

 - Aidbox image version: edge

**Additional context**

**Comment by KGOH** [comment]
Fixed on edge
