### ISSUE TITLE
[BUG] Capability statement includes invalid search parameter '_count'

### ISSUE THREAD

**Issue by Soyoung7533** [Aidbox/Issues#445]
**Describe the bug**
The capability statement includes `_count` as a search parameter for all resources. 

According to [fhir search](https://www.hl7.org/fhir/search.html#Summary) the `_count` is not a search parameter but rather a search result parameter. It should be removed from the `searchParam` list of the resources in the capability statement.

**Severity**
S1 - It gives misleading information to users. It causes validation error or Touchstone Provider Directory API test validation error.

**Steps to reproduce the behavior:**
Request: GET /fhir/metadata

The capability statement includes `_count` as a search parameter for all resources as below:

```
{
     "name": "_count"
     "definition": "http://hl7.org/fhir/SearchParameter/count-definition",
     "type": "number"
},
```

**Expected behavior**
 The `_count` should be removed from the `searchParam` list of the resources in the capability statement.

**Screenshots**

<img width="1035" alt="metadata response" src="https://user-images.githubusercontent.com/89491379/144138816-b1099ab9-d4f8-4064-8ecf-3da42f78e16f.png">

**Versions:**
- OS version

- Docker version (if applicable)

 - Aidbox image version
devbox:edge v:2111.151b06b8

 - Aidboxdb version (if applicable)

 - Browser version (if applicable)

 - Cloud provider (if applicable)

**Additional context**
Touchstone Conformance Test
https://touchstone.aegis.net/touchstone/scriptexecution?exec=202111301705048197229409&qn=/FHIR4-0-1-ProviderDir/DaVinci-PDEX-PlanNet/00-Capability/00-capabilities-json#WAITING_OPER

**Comment by ddegr** [comment]
Done
