### ISSUE TITLE
[BUG] Search mode is not set for the other resources in the `_include` and `_reinclude` search results

### ISSUE THREAD

**Issue by Soyoung7533** [Aidbox/Issues#446]
**Describe the bug**
The search mode is not set for the other resources in the `_include` and `_reinclude` search results

According to [fhir search](https://www.hl7.org/fhir/search.html#revinclude)
> For each returned resource, the server identifies the resources that meet the criteria expressed in the join, and adds to the results, with the entry.search.mode set to "include" (in some searches, it is not obvious which resources are matches, and which are includes). If there is no reference, or no matching resource, the resource cannot be retrieved (e.g. on a different server), then the resource is omitted, and no error is returned.

**Severity**
S1 - It gives misleading information to users. It causes validation error or Touchstone Provider Directory API test validation error.

**Steps to reproduce the behavior:**
GET /fhir/Endpoint?_include=Endpoint:organization

GET /fhir/HealthcareService?_revinclude=PractitionerRole:service

**Expected behavior**
The entry.search.mode sets to "include" 

**Screenshots**
<img width="1030" alt="healthcareService re-include search" src="https://user-images.githubusercontent.com/89491379/144141705-cb94fa23-a7b1-4c03-9ce8-4b6039de92bc.png">

**Versions:**
- OS version

- Docker version (if applicable)

 - Aidbox image version
devbox:edge v:2111.151b06b8

 - Aidboxdb version (if applicable)

 - Browser version (if applicable)

 - Cloud provider (if applicable)

**Additional context**
Touchstone Conformance Test

Scattered throughout search tests are warnings of the following type:

> WARNING: This is not a matching resource type for the specified search (is a search mode needed?) (Organization expecting [Endpoint]). Location: Bundle.entry[2] (line 1, col 2).

> These Warnings are pointing out that the search.mode on the included Organization entry is not populated, per the spec when adding other resources through an _include or _revinclude the server is to populate the search.mode element of those entries with the value ‘include’ so that clients understand how to use the resource. So, this should be corrected.

https://touchstone.aegis.net/touchstone/execution?exec=202111301705048197229409

**Comment by spicyfalafel** [comment]
Hello @Soyoung7533, we've implemented search.mode in the _include and _reinclude search results on `:edge`
