### ISSUE TITLE
$export patient/[patient-id] support - data related to patient and associated resources

### ISSUE THREAD

**Issue by ashwini-patil20** [Aidbox/Issues#452]
## Problem I need to solve
Need $export patient/[patient-id] support

## Solution I see
If the user hits $export/[patient-id] all data related to a patient and its associated resources should be exported.

**Comment by rublag** [comment]
We have implemented `patient` query parameter. https://docs.aidbox.app/api-1/bulk-api-1/usdexport#parameters
