### ISSUE TITLE
Add configurable Azure SAS expiration time

### ISSUE THREAD

**Issue by KGOH** [Aidbox/Issues#454]
## I need the following improvement
Default 30 is not often enough
https://docs.aidbox.app/storage-1/azure#get-shared-access-signature-sas-to-upload-file

## The expected benefit
Long $import doesn't fail if it takes more than 30 minutes

## Additional context
Critical. Promised to be delivered on 17 dec 2021

**Comment by Nesmeshnoy** [comment]
added configurable timeout https://docs.aidbox.app/storage-1/azure#get-shared-access-signature-sas-to-upload-file
