### ISSUE TITLE
Add count-query-time to the output for read operation

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#457]
Hi! 

I was trying to do this query, 
`get /Concept?system=http://snomed&_count=1`
and aidbox answers within 5-6 seconds (about 300000 concepts in the db)

but! query-time: 10

what is happening after executing the sql that it works so slow?

If I do the same query in the db console

```
    SELECT "concept".* FROM "concept" WHERE
    aidbox_text_search(knife_extract_text("concept".resource,
    $JSON$[["system"]]$JSON$)) ilike unaccent('% http://snomed%') LIMIT 1 OFFSET 0
```
aidbox answers immediately

[Edited]
Then I remembered about https://docs.aidbox.app/api-1/fhir-api/search-1/_total-or-_countmethod

_total=none helped, but was not obvious that the issue was caused by total.

I suggest adding count-query-time to the output of read operation. It will make debugging of this kind of issue more obvious.

**Comment by ruscoder** [comment]
Totally forgot about https://docs.aidbox.app/api-1/fhir-api/search-1/_total-or-_countmethod

_total=none helps, but it's not obvious that total is 'accurate' by default

**Comment by ruscoder** [comment]
Still actual, please pay attention on this

**Comment by Aitem** [comment]
Added.
For example you can run

```
GET /Attribute?_count=1&_totalMethod=accurate
```

Response 

```
query-time: 13
type: searchset
resourceType: Bundle
total: 8114
query-timeout: 60000
total-time: 8
entry:
  - resource: .....
```

Also you can check duration of count query via logs
![Screen Shot 2022-03-04 at 15 58 02](https://user-images.githubusercontent.com/1309701/156767654-ef7f24f3-2cec-4049-91b3-f0ac301b02bf.png)

**Comment by Nesmeshnoy** [comment]
@ruscoder please try it out and let us know if it works on your side.
