### ISSUE TITLE
Add pagination to _history endpoints

### ISSUE THREAD

**Issue by renom** [Aidbox/Issues#460]
```
GET /fhir/Patient/patient_id/_history?page=1
GET /fhir/Patient/patient_id/_history?page=2
...
GET /fhir/Patient/patient_id/_history?page=N
```

**Comment by ddegr** [comment]
Done. Please, use `Aidbox:egde`. Following parameters were added according to [FHIR Search spec](https://www.hl7.org/FHIR/search.html):

- `_page`
- `_count`

Please, give it a try and let us know if it works you well.
