### ISSUE TITLE
[BUG] _profile search parameter

### ISSUE THREAD

**Issue by ashwini-patil20** [Aidbox/Issues#461]
**Describe the bug**
If we hit following query with _profile as search parameter:  fhir/Patient?_profile=http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient

It returns response saying: No search parameter for Patient.profile

**Steps to reproduce the behavior:**
1. Enable zen profiling
2. Make an API call with the following search params '_profile'

**Expected behavior**
We want _profile search parameter to work as per FHIR

 - Aidbox image version
 edge

**Comment by ddegr** [comment]
Added search parameter `_profile` at edge. Documentation is [here](https://docs.aidbox.app/api-1/fhir-api/search-1/_profile)
