### ISSUE TITLE
Add disabling 'query' field in response contents to GET/$query/<aibbox-query-id>

### ISSUE THREAD

**Issue by salekseevmm** [Aidbox/Issues#462]

**Comment by Nesmeshnoy** [comment]
@salekseevmm can you try it and let us know your feedback?

**Comment by salekseevmm** [comment]
i will 

> @salekseevmm can you try it and let us know your feedback?

yes, as far as possible

**Comment by salekseevmm** [comment]
@Nesmeshnoy testing feature at devbox:edge v:2201.4ad886e0, no changes found. Some extra param or header is needed maybe?

**Comment by KGOH** [comment]
@salekseevmm please add attribute `"omit-sql": true` to your `AidboxQuery` to enable omitting sql

**Comment by salekseevmm** [comment]
oh, thanks)

**Comment by salekseevmm** [comment]
tests done, feature works properly
thanx)
