### ISSUE TITLE
Allow more complex functionality for $path! expressions in SDC extraction

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#463]
## Problem I need to solve

When using [Aidbox SDC](https://docs.aidbox.app/app-development-guides/tutorials/sdc-with-custom-resources), we would like to have the ability to use more complex expressions for `$path!` substitution rules.
For example if we would have a QuestionnaireResponse like:
```
{
    "resourceType": "QuestionnaireResponse",
    "id": "qr1",
    "questionnaire": "Questionnaire/q1|1",
    "item": [{
        "text": "What is your height in feet.inches?",
        "answer": [{
            "valueDecimal": 5.2
        }],
        "linkId": "ht"
    }, {
        "text": "What is your weight in pounds?",
        "answer": [{
            "valueDecimal": 122
        }],
        "linkId": "wt"
    }]
}
```
It is desired to be able to filter the `item`, let's say for example by `linkId: wt` and then be able to select the corresponding `valueDecimal` field. With the current support it's only possible to use plain expressions that does not allow to select items in an array neither filter those items.

## Solution I see

If we could use a more complex expression in `$path!` substitution rules, like `[ item, {"linkId": ht"}, answer, 0, valueDecimal ]` then it would be possible to complete the desired extraction of the data.

**Comment by ddegr** [comment]
Done. Available at `Aidbox:edge`

Now you can use expressions like `[ item, {"linkId": ht"}, answer, 0, valueDecimal ]`.

Please, give it a try and let us know if it works for you.

**Comment by ApricotLace** [comment]
[Documented](https://docs.aidbox.app/app-development-guides/tutorials/sdc-with-custom-resources#advanced-substitution-rules-examples)
