### ISSUE TITLE
[BUG] Search with _lastUpdated param does not work with /fhir/ prefix.

### ISSUE THREAD

**Issue by m-onyshchuk** [Aidbox/Issues#470]
**Describe the bug**
Search with _lastUpdated param does not work with /fhir/ prefix. 

**Severity**
Minor

**Steps to reproduce the behavior:**
1) Create some resources, for example, Bundle.
2) Send GET request to search Bundles with future date, for example: /fhir/Bundle?_lastUpdated=ge2024-01-01
3) You will got all Bundle resources
Query  /Bundle?_lastUpdated=ge2024-01-01 works fine (empty result set).  

**Expected behavior**
Empty result set for future dates.

**Screenshots**
There are no screenshots

**Versions:**
edge

 - Aidbox image version:
 edge

**Additional context**
No other context

**Comment by Nesmeshnoy** [comment]
@m-onyshchuk please test it on latest `edge`
