### ISSUE TITLE
[BUG] Parameters aidbox->FHIR transformation not working

### ISSUE THREAD

**Issue by tommymarlboro** [Aidbox/Issues#476]
**Describe the bug**
Incorrect formatting resource Parameters from Aidbox to FHIR format.¸
Resources in Parameters.parameter.n.resource containing attributes (in Aidbox format) "definition", "author", "offset", "timing" and etc.. not formatting in FHIR format. 

**Severity**
Critical

**Steps to reproduce the behavior:**

1. Prepared Parameter resource in attachment 
2. Make an API call `POST /$to-format/fhir`
3. Receive the following errored response. 

**Expected behavior**
Parameters.parameter.1.resource.action.0.definition -> Parameters.parameter.1.resource.action.0.definitionCanonical
Parameters.parameter.1.resource.action.0. relatedAction.0.offset -> Parameters.parameter.1.resource.action.0. relatedAction.0.offsetRange

**Versions:**
devbox:stable v:2111.f7bf3af9
devbox:edge v:2201.25205e19
[resourceParameters.txt](https://github.com/Aidbox/Issues/files/8096464/resourceParameters.txt)

**Comment by KGOH** [comment]
Fixed on edge

**Comment by tommymarlboro** [comment]
Thank you!
