### ISSUE TITLE
[BUG] Okta integration example in documentation does not work

### ISSUE THREAD

**Issue by gravesee** [Aidbox/Issues#477]
**Describe the bug**
Following the identity provider example for Okta results in an error when trying to get the auth token. This is possibly due to the aidbox/auth module sending client credentials in the json body as well as the request header which Okta does not allow.

**Severity**
Critical - we have a client who wants us to implement sso for their users using their Okta identity provider. We are open to custom workarounds to patch the behavior if there is an issue with the auth module.

**Steps to reproduce the behavior:**
1. Register an application with Okta and create a test user
2. Add the IdentityProvider resource to Aidbox
3. Attempt to sign in using Oauth as the test user from step 1.
4. Error in aidbox 

```
16:19:29 w3 GET /auth/callback/okta?code=YFoR0S4mxipX8iW3wcuc8tWE_CLJG3QVzcHQ116Zztk&state=Y2xpZW50X2lkPWFwcCZyZXNwb25zZV90eXBlPWNvZGU%3D
supdoc-aidbox-aidbox-1         | 16:19:29 w3 policy auth-public-endpoints
supdoc-aidbox-aidbox-1         | 16:19:29 w3 [2ms] SELECT * FROM "identityprovider" WHERE "id" = ? ["okta"]
supdoc-aidbox-aidbox-1         | 16:19:31 :error w3 clj-http: status 401 :auth/get-token-error {:msg "Cannot get access token", :ctx "17688a8f-34bd-4a0c-8346-58dcffb5ec62"}
supdoc-aidbox-aidbox-1         | 16:19:31 w3 [1238ms] 500
```
Errors in Okta logs:
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/1675613/154994095-8d4db863-2d1b-4ff3-bb3f-c3ae05af2e71.png">

There are lots of dev forum questions about this response text. For example: https://devforum.okta.com/t/error-cannot-supply-multiple-client-credentials/10307/6

**Expected behavior**
The response should be successful and both an access_token and id_token should be returned.

**Versions:**

 - Aidbox image version: 0.5.0-SNAPSHOT

**Comment by Nesmeshnoy** [comment]
@gravesee OKTA integration was introduced in `v:2107 stable` release 

https://docs.aidbox.app/getting-started/versioning-and-release-notes/release-notes#july-2021-v-2107-stable

Please consider updating to `v:2107 stable` or later version to get it working as the documentation states.
