### ISSUE TITLE
ConceptMap in the FHIR format

### ISSUE THREAD

**Issue by JustAsWalker** [Aidbox/Issues#481]
## Problem I need to solve
[This documentation](https://docs.aidbox.app/terminology/usdtranslate-on-conceptmap) describes that all resources ConceptMap will be transform into banch of ConceptMapRules. We need ability to get and operate with full version of the resource ConceptMap as it is described in [FHIR](https://www.hl7.org/fhir/conceptmap.html).

## Solution I see
It could be:
* get-endpoint that returns full ConceptMap by its id (or using aidbox / fhir API)
* parameter that defines the resource saving format (full or parsed as ConceptMapRules)
* something else

**Comment by Nesmeshnoy** [comment]
@JustAsWalker could you please try it and let us know it works as expected?

**Comment by JustAsWalker** [comment]
@Nesmeshnoy could you please point me to the part of documentation where this new feature is described or give me quick summary of changes?

**Comment by KGOH** [comment]
@JustAsWalker, hello. Here's the doc on how getting a full resource works: https://docs.aidbox.app/terminology/usdtranslate-on-conceptmap#how-to-get-full-conceptmap-resource

**Comment by JustAsWalker** [comment]
Checked feature, all is ok. Thanks for it and for documentation.
