### ISSUE TITLE
Pagination links should use the same URL encoding as the original request

### ISSUE THREAD

**Issue by russgray** [Aidbox/Issues#483]
## I need the following improvement
I am doing a lot of searches based on identifiers, and the system field is usually a url so my search criteria might be something like 
`https://github.com/synthetichealth/synthea|f2babb60-f2f2-5b08-5e60-1950ba7e88d6`

When I make the request I urlencode this as it contains various special characters, so my actual query might look like 
`/fhir/Observation?subject:Patient.identifier=https%3A%2F%2Fgithub.com%2Fsynthetichealth%2Fsynthea%7Cf2babb60-f2f2-5b08-5e60-1950ba7e88d6`.

In the response, however, the pagination links are not encoded. They look something like: 
```json
  "link": [
    {
      "relation": "first",
      "url": "/fhir/Observation?_elements=id&_count=2&subject:Patient.identifier=https://github.com/synthetichealth/synthea|f2babb60-f2f2-5b08-5e60-1950ba7e88d6&page=1"
    },
    {
      "relation": "self",
      "url": "/fhir/Observation?_elements=id&_count=2&subject:Patient.identifier=https://github.com/synthetichealth/synthea|f2babb60-f2f2-5b08-5e60-1950ba7e88d6&page=1"
    },
    {
      "relation": "next",
      "url": "/fhir/Observation?_elements=id&_count=2&subject:Patient.identifier=https://github.com/synthetichealth/synthea|f2babb60-f2f2-5b08-5e60-1950ba7e88d6&page=2"
    },
    {
      "relation": "last",
      "url": "/fhir/Observation?_elements=id&_count=2&subject:Patient.identifier=https://github.com/synthetichealth/synthea|f2babb60-f2f2-5b08-5e60-1950ba7e88d6&page=53"
    }
  ]
```

I have to do some processing on these urls before I can use them; it would be easier (and I think more consistent) if they retained the encoding from the original request.

## The expected benefit
Pagination links will more closely mirror the original request rather than requiring re-encoding each time

**Comment by rublag** [comment]
Fixed during release review by dd42eafdb01e085f58673320cd8851a82f866245. Introduced by 840be8aaead553b65c23c0473d9f3b0e361eccf8
![image](https://user-images.githubusercontent.com/2961967/157890978-485c2d36-e386-4d58-9828-7333a24ae6fc.png)

**Comment by rublag** [comment]
Fixed.

**Comment by Nesmeshnoy** [comment]
@russgray сould you please check it on `:edge` and let us know if it works as expected on your side?
