### ISSUE TITLE
Unable to execute complex SQL using DB Console/Notebooks

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#484]
## I need the following improvement
Previously Aidbox had a button named Execute, that allowed us to execute complex SQL (see example below)

```sql
DROP FUNCTION IF EXISTS drop_before_all(integer);
CREATE FUNCTION drop_before_all(integer) RETURNS VOID AS $$
declare
e record;
BEGIN
FOR e IN (select LOWER(entity.id) as t_name from entity where resource#>>'{type}' = 'resource' and id != 'OperationOutcome') LOOP
    EXECUTE 'delete from "' || e.t_name || '" where txid > ' || $1 ;
END LOOP;
END;
$$ LANGUAGE plpgsql;
```

Now it's impossible.

It always returns evaluation line-by-line splitted by ';'

```
No results were returned by the query.
Unterminated dollar quote started at position 58 in SQL CREATE FUNCTION drop_before_all(integer) RETURNS VOID AS $$ declare e record. Expected terminating $$
ERROR: syntax error at or near "FOR" Position: 8
ERROR: syntax error at or near "LOOP" Position: 6
No results were returned by the query.
Unterminated dollar quote started at position 1 in SQL $$ LANGUAGE plpgsql. Expected terminating $$
```

## The expected benefit

Return back `Execute` button that executes the entire code without splitting it by `;` and executing line by line.

## Additional context

I assume /$psql?execute=true still exists for that case that was previously used for Execute button, so, it shouldn't be an issue. I believe Execute was removed by mistake. I always use DB console for debugging, and creating functions is one of examples.

**Comment by ruscoder** [comment]
Ah, found a way of doing it using Notebooks. Closing it.

**Comment by ruscoder** [comment]
Found that it does not work in notebooks as well. Notebooks execute only the first line

<img width="1057" alt="Screenshot 2022-03-15 at 13 49 05" src="https://user-images.githubusercontent.com/3920871/158361734-8f7b61b8-f36b-47b2-bf38-d375caff6fde.png">

**Comment by ruscoder** [comment]
<img width="1011" alt="Screenshot 2022-03-15 at 13 49 39" src="https://user-images.githubusercontent.com/3920871/158361836-c536e061-cfd9-4105-8485-7de3460f7b7f.png">

**Comment by ruscoder** [comment]
My Notebook: https://aidbox.app/ExportedNotebook/c3fefeb3-18c5-4601-b790-cd7a08b7f115

**Comment by Nesmeshnoy** [comment]
@ruscoder available for notebooks on `:edge`. Please check it on your side.

**Comment by ruscoder** [comment]
Works for me. Thanks!

**Comment by MFAshby** [comment]
I'm hitting this same issue in the db console still:
```
select ';';
```
errors with 
```
Unterminated string literal started at position 7 in SQL select '. Expected char
Unterminated string literal started at position 0 in SQL '. Expected char
```

**Comment by vganshin** [comment]
Hi @MFAshby

Currently db console splits provided query by semicolon `;` and executes them separately. So you will get two results by one request. Example:

```sql
select * from patient where id = 'pt-1';
select * from encounter where resource#>>'{subject,id}' = 'pt-1';
```

This is why your request `select ';';` breaks. Aidbox notebooks doesn't such feature as every cell in notebook runs atomically.

As for db console, we would like to keep query separating functionality, but we agree that `;` is not a good delimeter as you might want to declare stored procedure or run some transaction. We are considering to change query delimiter from semicolon to 4 dashes on a new line.

```sql

select * from patient where id = 'pt-1';
select * from encounter where resource#>>'{subject,id}' = 'pt-1';

-- 4 dashes will work as delimiter for queries, instead of semicolon
----

-- Some comment here

begin;

delete from patient where id = 'pt-1';
delete from encounter where resource#>>'{subject,id}' = 'pt-1';

end;

```

It will enable writing more complex sql queries like stored procedures or transaction and it will keep ability to run few queries in one request.

We will appreciate any feedback on that.

**Comment by MFAshby** [comment]
> We will appreciate any feedback on that.

Thanks for looking!

I think using ---- as separator would be fine, it may also be worth putting a help on the db console page to highlight this behaviour to the user.

**Comment by vganshin** [comment]
To mention it directly on db console sounds good. Thanks.

**Comment by krevedkokun** [comment]
Hi, @MFAshby, we've implemented it on :edge channel. Please check it
out and let us know how it works for you.
