### ISSUE TITLE
[BUG] Bundle resource contains unexpected element "total-time" on FHIR search calls with patient resource predicate

### ISSUE THREAD

**Issue by solventusllc** [Aidbox/Issues#485]
Bundle resource contains unexpected element "total-time" on FHIR search calls with patient resource predicate. The unexpected element causes FHIR.NET parser to fail.

**Severity**
Major.

**Steps to reproduce the behavior:**
Box with FHIR v 4.0.0.

Sample API Call:
https://solventustest.aidbox.app/fhir/Observation?subject=Patient%2Ffc47806b-3b22-4003-9ff6-5e9c927a8677

Result:
  "resourceType": "Bundle",
    "type": "searchset",
    "meta": {
        "versionId": "256"
    },
    "total": 240,
    "total-time": 16,...

**Expected behavior**
  "resourceType": "Bundle",
    "type": "searchset",
    "meta": {
        "versionId": "256"
    },
    "total": 240,
"link": [
        {
            "relation": "first",
            "url": "/fhir/Observation?subject=Patient%2Ffc47806b-3b22-4003-9ff6-5e9c927a8677&page=1"
        },
        {
            "relation": "self",
            "url": "/fhir/Observation?subject=Patient%2Ffc47806b-3b22-4003-9ff6-5e9c927a8677&page=1"
        },
        {
            "relation": "next",
            "url": "/fhir/Observation?subject=Patient%2Ffc47806b-3b22-4003-9ff6-5e9c927a8677&page=2"
        },
        {
            "relation": "last",
            "url": "/fhir/Observation?subject=Patient%2Ffc47806b-3b22-4003-9ff6-5e9c927a8677&page=3"
        }
    ],...

**Versions:**
Latest cloud version as of 3/15/2022

**Comment by ddegr** [comment]
@solventusllc, fixed on `aidbox:edge`
Can you please check if it works for you

**Comment by solventusllc** [comment]
No, still getting the same problem, both within my app and from Postman.
Here's the initial part of the response to the request:

https://solventustest.aidbox.app/fhir/Observation?subject=Patient%2Ffc47806b-3b22-4003-9ff6-5e9c927a8677

Response:
{
    "resourceType": "Bundle",
    "type": "searchset",
    "meta": {
        "versionId": "256"
    },
    "total": 240,
    "total-time": 20,
    "link": [
        {
            "relation": "first",
            "url":
"/fhir/Observation?subject=Patient%2Ffc47806b-3b22-4003-9ff6-5e9c927a8677&page=1"
        },
        {
            "relation": "self",
            "url":
"/fhir/Observation?subject=Patient%2Ffc47806b-3b22-4003-9ff6-5e9c927a8677&page=1"
        },
        {
            "relation": "next",
            "url":
"/fhir/Observation?subject=Patient%2Ffc47806b-3b22-4003-9ff6-5e9c927a8677&page=2"
        },
        {
            "relation": "last",
            "url":
"/fhir/Observation?subject=Patient%2Ffc47806b-3b22-4003-9ff6-5e9c927a8677&page=3"
        }
    ],
...

The problematic total-time element is still present.

Best regards,

Ken Miller
Solventus LLC

**Comment by ier** [comment]
Fixed on `latest`.

**Comment by Nesmeshnoy** [comment]
@solventusllc please try it out. Looks like you use `:latest`.

**Comment by solventusllc** [comment]
Confirmed fixed on my end.

Ken Miller
Solventus LLC
www.solventus.com
USA: (305) 349 3493
Canada: (416) 887 8534
