### ISSUE TITLE
Availability to add additional parameters to $lookup function

### ISSUE THREAD

**Issue by phjdreef** [Aidbox/Issues#496]
## Problem I need to solve
We use Aidbox (standard), with multiple organization's in 1 DB. We apply access-rules to limit the search-requests, based on parameters 
eg: /Patient?managingOrganization=.....

If we use [$lookup](https://docs.aidbox.app/api-1/fhir-api/search-1/usdlookup), there is no possibility to add extra parameters, and link them to resource-items

## Solution I see
Add additional parameters to the function, and follow the same approach like in the (SearchQuery) [https://docs.aidbox.app/api-1/fhir-api/search-1/searchquery]

**Comment by KGOH** [comment]
@pdreef-meditools, hello! $lookup operation supports [dot expressions](https://docs.aidbox.app/api-1/fhir-api/search-1/.-expressions).

For example:
```
GET /Patient/$lookup?\
  by=name.family,name.given,birthDate&\
  q=Joh+Do+1980&\
  .managingOrganization.id=org1
```

Is this something that suits your use case?
