### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nitishd599** [Aidbox/Issues#497]
Hi Team, can anyone please look into the issues I found while trying out the patient resource with filter _createdAt along with operators (gt, lt, ge, le). Below is the list of scenarios and issues encountered:
1) Endpoint -> /Patient?_createdAt=gt202 | Response -> Getting 200 response code with invalid year
2) Endpoint -> /Patient?_createdAt=gt2022-18 | Response -> Getting 500 response code with invalid month
3) Endpoint -> /Patient?_createdAt=gt2022-10-32 | Response -> Getting 500 response code with invalid day
4) Endpoint -> /Patient?_createdAt=gt2022-01-20T12:53:05.441435 | Response -> Getting 200 response code with invalid timezone
Similar behaviour is seen with operators lt, ge and le as well

**Severity**
Major

**Comment by ier** [comment]
Fixed on `Edge`. Please, enable [compliance mode](https://docs.aidbox.app/getting-started/installation/configure-devbox-aidbox-multibox#enable-aidbox-compliance-mode).
