### ISSUE TITLE
Unable to use $expand on /fhir/ValueSet

### ISSUE THREAD

**Issue by jyeros** [Aidbox/Issues#50]
I am trying to list all items of a value set with `$expand`. But when i try to do it inside `/fhir` i get `404`
```json
Status: 404
{
 "resourceType": "OperationOutcome",
 "id": "not-found",
 "text": {
  "status": "generated",
  "div": "Resource CompartmentDefinition/ValueSet not found"
 },
 "issue": [
  {
   "severity": "fatal",
   "code": "not-found",
   "diagnostics": "Resource CompartmentDefinition/ValueSet not found"
  }
 ]
}
```
If I do it direct to `[base]` all work god.
Summary:
`GET [base]/fhir/ValueSet/$expand?url=myurl` ❌ 
`GET [base]/fhir/ValueSet/myid/$expand` ❌ 
`GET [base]/ValueSet/$expand?url=myurl` ✅ 
`GET [base]/ValueSet/myid/$expand` ✅

**Comment by Aitem** [comment]
Hi @jyeros 
We are planned to move and support `Terminology` API under `/fhir` prefix in the next release 0.4.0
