### ISSUE TITLE
ConceptMap GraphQL

### ISSUE THREAD

**Issue by rmhayek** [Aidbox/Issues#502]
## I need the following improvement
GraphQL `ConceptMap` retrieval always returns `group = null`.

## The expected benefit
This causes confusion especially that creating a `ConceptMap` contains a group and Aidbox ungroups this field into a `ConceptMapRule`.   

One of 2 things might help:  
1- Add a link from `ConceptMap.group` to `ConceptMapRule` - this allows callers to go from group to concept map rule `group { ...on ConceptMapRule {...}}` - this is the preferable method.
OR
2- Add an exclusion to remove group from `ConceptMap` GraphQL.  This may still cause confusion but can be explained in the community notebook on concept maps and at least no null value can be retrieved.
## Additional context

Create a `ConceptMap` following the "FHIR ConceptMap Resource and translation" community notebook.
```
query {
  ConceptMapList {
    id
    group {
      id
    }
  }
}
```
The response:
```
{
  "data": {
    "ConceptMapList": [
      {
        "id": "101",
        "group": null
      }
    ]
  }
}
```

**Comment by ApricotLace** [comment]
Hello, @rmhayek!
Have you seen this query example? (Should work on edge)
```
query {
  ConceptMapRuleList(_count: 1000, conceptmapId: "101") {
    conceptmapId
    source
    target
    element
  }
}
```
Look like it suits your needs, please provide feedback about this query.

**Comment by rmhayek** [comment]
@ApricotLace we are using that query; however that's not the reason I'm requesting an enhancement.  
`group` is always `null` with GraphQL and that's very confusing to developers.  Using REST `GET /fhir/ConceptMap/101` I get the group in the response payload - it is not `null` where I have to also query `ConceptMapRuleList`; that's why I'm requesting this enhancement.  If `group` is a reference to `ConceptMapRuleList` or just returns the `group` array like REST API does, it would be a more consistent API.

**Comment by ApricotLace** [comment]
Hello, @rmhayek. We'll mount ConceptMapRuleList to group field.

**Comment by rmhayek** [comment]
Thank you @ApricotLace for adding the association - much appreciated!

**Comment by ApricotLace** [comment]
Hello, @rmhayek! We've implement this "linking", now you can get `group` attribute just like in REST API. Should be available on the latest `edge`.

Sample request:
```
query {
  ConceptMapList {
    id
    group {
      element {
        code 
        display
        target {
          code
          display
          equivalence
          comment
        }
      }
    }
  }
}
```

**Comment by rmhayek** [comment]
Verified latest edge, it's working well - Thank you @ApricotLace!
