### ISSUE TITLE
[BUG] POST same ConceptMap twice duplicates Rules

### ISSUE THREAD

**Issue by rmhayek** [Aidbox/Issues#503]
**Describe the bug**
Post the same concept map twice results in duplicate rules and duplicate `$translate` matches in the payload.
**Severity**
Major

**Steps to reproduce the behavior:**
1. Use the community notebook "FHIR ConceptMap Resource and translation"
2. Run the first command twice.
3. Run `$translate` command
4. The payload returned has duplicate match:
```
{
 "resourceType": "Parameters",
 "parameter": [
  {
   "name": "result",
   "valueBoolean": true
  },
  {
   "name": "match",
   "part": [
    {
     "name": "equivalence",
     "valueCode": "equivalent"
    },
    {
     "name": "concept",
     "valueCoding": {
      "system": "http://terminology.hl7.org/CodeSystem/v3-AddressUse",
      "code": "H",
      "userSelected": false,
      "display": "home"
     }
    },
    {
     "name": "source",
     "valueUri": "http://hl7.org/fhir/ConceptMap/101"
    }
   ]
  },
  {
   "name": "match",
   "part": [
    {
     "name": "equivalence",
     "valueCode": "equivalent"
    },
    {
     "name": "concept",
     "valueCoding": {
      "system": "http://terminology.hl7.org/CodeSystem/v3-AddressUse",
      "code": "H",
      "userSelected": false,
      "display": "home"
     }
    },
    {
     "name": "source",
     "valueUri": "http://hl7.org/fhir/ConceptMap/101"
    }
   ]
  }
 ]
}
```
**Expected behavior**
A single match must be returned.
```
{
 "resourceType": "Parameters",
 "parameter": [
  {
   "name": "result",
   "valueBoolean": true
  },
  {
   "name": "match",
   "part": [
    {
     "name": "equivalence",
     "valueCode": "equivalent"
    },
    {
     "name": "concept",
     "valueCoding": {
      "system": "http://terminology.hl7.org/CodeSystem/v3-AddressUse",
      "code": "H",
      "userSelected": false,
      "display": "home"
     }
    },
    {
     "name": "source",
     "valueUri": "http://hl7.org/fhir/ConceptMap/101"
    }
   ]
  }
 ]
}
```

**Screenshots**

**Versions:**

 - Aidbox image version:
edge: v:2202.37f1b274 and stable/latest as well.

**Additional context**
When looking at DB tables, posting once `ConceptMap`, creates a single `ConceptMap` with `id=101` and 4 `ConceptMapRule` with `id=uuid` autogenerated.
Post the same `ConceptMap` again, there will be a single `ConceptMap` with `id=101` and 8 `ConceptMapRule` with autogenerated `id`. 
This results in duplicate matches and in GraphQL duplicate values (different `id`) in `ConceptMapRuleList`

**Comment by rublag** [comment]
@rmhayek could you please provide more details on your context? Why do you need to POST the same ConceptMap resource multiple times?

**Comment by rmhayek** [comment]
@rublag `POST` is not idempotent.  So if done multiple times, new IDs are created for a resource without an ID.  In this case the `ConceptMap` has an ID and `POST` of the same resource twice should return `409 Conflict` (maybe with a link to the existing resource). 

"Why do you need to POST the same ConceptMap resource multiple times?"
I don't need that as a feature.  I noticed duplication of matching rules in our environment, so I ran the notebook twice and saw that `ConceptMapRule` resources are created even when the `ConceptMap` ID already exists in the database.  I would like it to nicely fail so mistakes like this can be circumvented in deployed environments.

**Comment by ApricotLace** [comment]
Hello, @rmhayek. We can fix in the following way:
Uniqueness of ConceptMap will be defined by these fields: `url` OR `id`.

If these fields are not presented, Aidbox will create a new `ConceptMap` AND new `ConceptMapRule` resources.

If these fields are presented and there is **already** `ConceptMap` resource with this `id` OR `url` in Aidbox, Aidbox will update existing `ConceptMap` resource, delete old `ConceptMapRule` resources and create new ConceptMapRules.

Do you think it will work for you?

**Comment by rmhayek** [comment]
Hi @ApricotLace - `url` can be equal across a set of concept maps - the unique combination would be `url` + `version`.  We can have different versions of a ConceptMap.  They would have different `id`, same `url`, different `version` and associated rules may or may not be the same.  That's why separating `group` into `ConceptMapRule` is difficult to maintain without `Map <-> Rule` bi-directional association.

**Comment by Nesmeshnoy** [comment]
@rmhayek available on `:edge`. Please try it out and let us know if it works as expected.

**Comment by rmhayek** [comment]
@Nesmeshnoy I did `make update` and tried it with `devbox:edge v:2204.91f19632` - it still inserts duplicate ConceptMapRules if the same ConceptMap is posted twice.  Do I have the correct `edge` version?

**Comment by krevedkokun** [comment]
@rmhayek sorry for the confusion. I'll close the issue when fix would be avaliable on edge

**Comment by krevedkokun** [comment]
@rmhayek should be avaliable on edge now

**Comment by rmhayek** [comment]
@krevedkokun Thank you!  It works now.
