### ISSUE TITLE
Need support for FHIR Subscription

### ISSUE THREAD

**Issue by pappuks** [Aidbox/Issues#504]
## Problem I need to solve
We need expose subscriptions to our FHIR API consumers. 

## Solution I see
I need implementation of FHIR Subscription https://www.hl7.org/fhir/subscription.html

## Alternatives I've considered, but they don't work
The Aidbox subscriptions https://docs.aidbox.app/api-1/reactive-api-and-subscriptions/subscriptions-1 is a custom implementation, and is not something which we would want to expose to our FHIR API consumers.

**Comment by pappuks** [comment]
It will be great if we can implement the R4B Subscription and SubscriptionStatus.

**Comment by VarvaraSemenova** [comment]
@pappuks Hi! As we are moving forward subscriptions support in Aidbox, could you please answer a couple of questions?
1. What is the preferred channel for receiving notifications for you/your customers when using subscriptions? (rest-hook,
websocket, email/sms, message)
2. Could you give us use cases you/your customers are going to cover with subscriptions?

**Comment by pappuks** [comment]
Hi,

1. Rest-hook is the preferred method.
2. The use case we are looking for is to sync two FHIR servers with any
updates, so in this case we need notifications for CRUD operations on all
resources. We also need notifications for additional query parameters for
each resource, the same query parameters which are supported by the search
endpoint.

Feel free to ask any further questions.

Regards,
Kuldeep

**Comment by mput** [comment]
@pappuks
To make it clear. We are going to implement Subscription R5 backport to R4B according to this [IG](http://build.fhir.org/ig/HL7/fhir-subscription-backport-ig/)

I'll prepare a list of what part of the specification will be available from the start, but it should contain the functionality you mentioned in the above message.

**Comment by pappuks** [comment]
Sounds good!

**Comment by spicyfalafel** [comment]
https://docs.aidbox.app/modules/topic-based-subscriptions
