### ISSUE TITLE
Add support for Oracle Cloud Storage

### ISSUE THREAD

**Issue by rekotan** [Aidbox/Issues#507]
## Problem I need to solve

For the cloud storage options, currently AWS, GCP, and Azure are supported. We'd like it to expand to OCI as well.

## Solution I see

Similar to other cloud providers (e.g. `AzureAccount`), we could configure OCI account so we can read data from Oracle Cloud Storage.

## Alternatives I've considered, but they don't work

The main use case is to bulk load resources. Alternative is to call REST APIs for each resource, which has huge performance implication.

## Additional context

https://docs.aidbox.app/storage-1/azure
https://www.oracle.com/cloud/storage/
https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/usingpreauthenticatedrequests.htm

**Comment by artuaa** [comment]
# Import from oracle storage

## Steps to reproduce
Put test file
```sh
curl -X PUT --data-binary '@<path-to-local-file>' <signed-url>/fhri-import.ndjson.gz
```
File url
```sh
<signed-url>fhri-import.ndjson.gz
```
Aidbox bulk import
```
POST /fhir/$import
Accept: text/yaml
Content-Type: text/yaml

id: oracle-test
inputFormat: application/fhir+ndjson
contentEncoding: gzip
mode: bulk
inputs:
- resourceType: Patient 
  url: <signed-url>/fhri-import.ndjson.gz
```

Check import status
```
GET /BulkImportStatus/oracle-test
```

**Comment by rekotan** [comment]
With pre-authenticated requests, the import worked with OCI buckets. Thanks for the direction.
