### ISSUE TITLE
Add logging for custom operations timeout

### ISSUE THREAD

**Issue by pavlushkin** [Aidbox/Issues#510]
## Problem I need to solve
I have an Aidbox with a python app and custom operations. These operations are part of API exposed to external clients. Sometimes the operations reach timeout. I would like to know when it happens.

## Solution I see
Add log records when a custom operation reaches timeout.

## Alternatives I've considered, but they don't work
I explored existing logs generated by Aidbox and found no relevant items.

**Comment by krevedkokun** [comment]
@pavlushkin, hello. we have added log with :op/timeout ev. please try it and let us know if it works for you

**Comment by pavlushkin** [comment]
@krevedkokun hello, I used image: "healthsamurai/devbox:edge" and it did not work for me. What image should I try?

**Comment by krevedkokun** [comment]
@pavlushkin `devbox` is deprecated, use `aidboxone` image with dev-license

**Comment by pavlushkin** [comment]
It works for me, thank you!
