### ISSUE TITLE
Providing the choice of FHIR or IG package version to zen fhir packages 

### ISSUE THREAD

**Issue by Bijitakc** [Aidbox/Issues#514]
## I need the following improvement
I would like to be able to choose the FHIR or IG version in the zen fhir packages. This will allow me to configure multiple versions of the FHIR or IG in aidbox when profiling with zen-lang. 

## The expected benefit
This will enable the aidbox users to accept and validate data from multiple fhir or IG versions since currently only the latest version can be used.

**Comment by KGOH** [comment]
@Bijitakc Hello. We added different FHIR IG versions support to our zen package github repo. Please check it out and write back if it works for you
https://github.com/zen-lang/fhir/releases/latest
