### ISSUE TITLE
Use yaml files for seeds in zen project

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#518]
## I need the following improvement
The only way to define seeds for the zen project is to embed them to .edn files like this
```
{ns sdc-box
 import #{aidbox.rest vitals}

 box
 {:zen/tags #{aidbox/system}
  :zen/desc "test server"
  :services {:seed-fixtures seed-fixtures}}

 seed-fixtures
 {:zen/tags  #{aidbox/service}
  :engine    aidbox/seed
  :resources {:Client {:SPA {:grant_types ["password"]}}}}
}
```
It works fine with small resources like `Client`.

However, it is more convenient to place big resources like `Questionnaire` into separate yaml files like this:
https://github.com/beda-software/fhir-emr/tree/master/backend/resources/entities/Questionnaire

**Comment by rublag** [comment]
@ir4y, although yaml is not currently supported, you can [use .ndjson.gz files for seeds](https://docs.aidbox.app/aidbox-configuration/aidbox-zen-lang-project#seed-import).

**Comment by ir4y** [comment]
Hi @rublag 

ndjson.gz - is a compressed format. So I can't just edit it and introspect via github/gitlab web UI. 
I have to unpack, then edit, then pack. It is not convenient.
