### ISSUE TITLE
[BUG] The FHIR metadata request does not return the URLs under the FHIR base URL in the CapabilityStatement 

### ISSUE THREAD

**Issue by Soyoung7533** [Aidbox/Issues#519]
**Describe the bug**
The FHIR metadata request does not return the URLs under the FHIR base URL in the CapabilityStatement 

**Severity**
S1 - It blocks the URL processing

**Steps to reproduce the behavior:**
Send metadata request to Aidbox

Request: GET /fhir/metadata
Headers:
Accept - application/fhir+json;charset=UTF-8
Content-Type - application/json;charset=UTF-8

Response: The response content is the CapabilityStatement with the URLs that are not under the FHIR base URL.
```
{
         "name": "appointment-type",
         "definition": "http://fhir.sandbox.rhapsody.global:8888/SearchParameter/Appointment.appointment-type",
          "type": "token"
}
```

**Expected behavior**
The response content is the CapabilityStatement  with the URLs that are under the FHIR base URL, for example
```
{
         "name": "appointment-type",
         "definition": "http://fhir.sandbox.rhapsody.global:8888/fhir/SearchParameter/Appointment.appointment-type",
          "type": "token"
}
```

**Screenshots**
<img width="1030" alt="metadata response" src="https://user-images.githubusercontent.com/89491379/176337001-b9314ccf-cbbb-4678-bcb0-454773b52fe1.png">

**Versions:**

**OS version**

**Docker version (if applicable)**

**Aidbox image version**
Stable

**Aidboxdb version (if applicable)**

**Browser version (if applicable)**

**Cloud provider (if applicable)**

**Additional context**

**Comment by spicyfalafel** [comment]
@Soyoung7533 
We fixed it on :edge, please check if if works for you.

**Comment by Soyoung7533** [comment]
Thanks. When can this feature be available in the stable version?

**Comment by spicyfalafel** [comment]
@Soyoung7533 
It will be available at :latest on July 3 and will appear on :stable version in a month.
