### ISSUE TITLE
Urgent: Unable to use token generated through OAuth2 Credentials, getting 401 and 403 errors.  

### ISSUE THREAD

**Issue by PavanPatro-Innovaccer** [Aidbox/Issues#520]
## Question

Token(JWT) obtained through oAuth2 client credentials doesn’t work getting 401 “unauthorised” as response. Token(without JWT) obtained through oAuth2 client credentials doesn’t work getting 403 “Forbidden” as response.

**Comment by VarvaraSemenova** [comment]
Please provide the steps to reproduce
Also please run the $version and send us the response (to get your Aidbox version)

**Comment by PavanPatro-Innovaccer** [comment]
version: '2206'
channel: edge
commit: 549985f34
zen-fhir-version: 0.5.13

**Comment by PavanPatro-Innovaccer** [comment]
steps to reproduce: 
1.create a client ->
secret: somesecret
auth:
  client_credentials:
    token_format: jwt
    refresh_token: true
    access_token_expiration: 3600
grant_types:
  - client_credentials
_source: code
first_party: true
id: test
resourceType: Client


2. generate access token -
{"client_id": "test",
 "client_secret": "somesecret",
 "grant_type": "client_credentials"
}
 3. use this access token to access any rest api (/fhir/Patient or /Observation)

4. you will get 401

**Comment by VarvaraSemenova** [comment]
1. Please make sure you've reviewed the tutorial https://docs.aidbox.app/security-and-access-control-1/auth/client-credentials
2. Also, please check the interactive Auth tutorial located under AuthSandbox on the left panel in Aidbox UI

![image](https://user-images.githubusercontent.com/30662300/176699572-f6e23fcd-49ee-4f61-adef-3d2282de546a.png)

**Comment by PavanPatro-Innovaccer** [comment]
I have tried this. and still it's a no go ..

**Comment by sandeshchoudhary** [comment]
@PavanPatro-Innovaccer This issue is resolved. Please close this ticket. @VarvaraSemenova wrong configmap with jwt check skip marked true was getting passed to the container. We have fixed the configmap provided for the deployment.

**Comment by PavanPatro-Innovaccer** [comment]
Issue Resolved.
