### ISSUE TITLE
Urgent : Need a new key named "profile" and have the contents same as "supportedProfile" key

### ISSUE THREAD

**Issue by PavanPatro-Innovaccer** [Aidbox/Issues#522]
need the contents of CapabilityStatement.rest.resource.suppportedProfile in  CapabilityStatement.rest.resource.profile key

Note:  here the CapabilityStatement is same as /metadata

**Comment by VarvaraSemenova** [comment]
Hi, please specify the priority of the task: is it a blocker?

**Comment by PavanPatro-Innovaccer** [comment]
Yes, @VarvaraSemenova , our client is strictly referring to the FHIR spec, which also mentions, the content should have been there on CapabilityStatement.rest.resource.profile key. 
Please consider this as high priority line item.

**Comment by PavanPatro-Innovaccer** [comment]
@VarvaraSemenova  Any update on this ?

**Comment by rublag** [comment]
@PavanPatro-Innovaccer, implemented. Try on the most recent edge build.

**Comment by PavanPatro-Innovaccer** [comment]
@rublag and @VarvaraSemenova  will surely check and get back to you.

**Comment by VarvaraSemenova** [comment]
@PavanPatro-Innovaccer Hi, have you got a chance to try it?
