### ISSUE TITLE
Sync terminology upload

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#523]
## I need the following improvement
When I run integration tests, I need a fully initialized Aidbox.
I am using __healthcheck to ensure that Aidbox is ready.

## The expected benefit
I expect terminology is uploaded to Aidbox when __healthcheck is ready

## Additional context
Terminology is uploading asynchronously, so tests start before uploading is finished, so tests fail.

**Comment by krevedkokun** [comment]
@ir4y we have added `box_features_terminology_import_sync` environment variable. check out [documentation](https://docs.aidbox.app/getting-started/installation/configure-devbox-aidbox-multibox)

**Comment by ir4y** [comment]
It worked! Thank you.
