### ISSUE TITLE
[BUG] Can't set isUnique restriction to attribute on an entity using NodeJS SDK

### ISSUE THREAD

**Issue by ArmellaJuan** [Aidbox/Issues#527]
**Describe the bug**
When using `NodeSDK` I can't create an entity with a unique attribute.

**Severity**
Major

**Steps to reproduce the behavior:**
1. Create an AidboxApp with the next entity:

```
const Entity = {
  attrs: {
    adtRecordId: {
      type: 'id',
      unique: true
    }
  }
};
```
or
```
const Entity = {
  attrs: {
    adtRecordId: {
      type: 'id',
      isUnique: true
    }
  }
};
```

**Expected behavior**
It should create an entity with an `adtRecordId` attribute that has the `isUnique: true` restriction.

**Screenshots**
I receive this error when I try to do that: (Used the same request via POSTMAN on the `[PUT] /APP` endpoint with the same schema)

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/5683181/182930356-0c46152f-6abc-4bcb-b5cb-a6c44981c7bf.png">

```
{
    "resourceType": "OperationOutcome",
    "id": "invalid",
    "text": {
        "status": "generated",
        "div": "Cannot save manifest because of errors: [{:path [:entities :Entity :attrs :adtRecordId :isUnique], :message \"extra property\"}]"
    },
    "issue": [
        {
            "severity": "fatal",
            "code": "invalid",
            "diagnostics": "Cannot save manifest because of errors: [{:path [:entities :Entity :attrs :adtRecordId :isUnique], :message \"extra property\"}]"
        }
    ]
}
```

Also the error in the app console:
![image](https://user-images.githubusercontent.com/5683181/182930504-daf9ad4f-5f89-4817-b16d-628200fcade8.png)

**Versions:**
 - Aidbox image version:
`devbox:stable v:2205.0f45af30`

**Additional context**
I can do this via the REST API setting `isUnique: true` in the entity but when I reload the app the entity is overwritten and the attribute no longer has that restriction.

**Comment by VarvaraSemenova** [comment]
Hi, thank you for reporting the issue. Bug is confirmed, estimated fix delivery time is Aug, 9

**Comment by krevedkokun** [comment]
@ArmellaJuan, hi. We fixed your issue, it's available on :edge. Please pull new version and let us know if it's working for you.

**Comment by ArmellaJuan** [comment]
Cool after switching to that image seems working:

```adtRecordId: {
      type: 'id',
      isUnique: true
    },
```

And in devbox:
<img width="415" alt="Screen Shot 2022-08-09 at 10 10 22 AM" src="https://user-images.githubusercontent.com/5683181/183655169-168c0904-c424-49a0-ad53-728f68b6f228.png">

Thanks!
