### ISSUE TITLE
Aidbox FHIR Capability Statement not conforming to the standard (missing date & status fields) [BUG]

### ISSUE THREAD

**Issue by antpyykk** [Aidbox/Issues#529]
**Describe the bug**
Aidbox Capability Statement does not seem to be conforming to the FHIR R4 [CapabilityStatement](https://www.hl7.org/fhir/R4/capabilitystatement.html) definition.

The response does not seem to have the `date` & `status` fields, which are marked as required.

**Steps to reproduce the behavior:**
This bug became apparent when we used the python library [fhirclient](https://github.com/smart-on-fhir/client-py).
When initializing, the client will call the metadata endpoint (`/fhir/metadata`), but fails when it expects the relevant fields to be there.

**Expected behavior**
The capability statement should contain the required fields for CapabilityStatement.

**Versions:**

 - Aidbox image version:
aidbox:edge
v:2206.ee0932142

**Additional context**

**Comment by krevedkokun** [comment]
@antpyykk, hi, could you share more details? it seems to be working fine for us

**Comment by krevedkokun** [comment]
@antpyykk hello. could you try to set up [AIDBOX_COMPLIALCE=enabled](https://docs.aidbox.app/reference/configuration/environment-variables/optional-environment-variables#enable-aidbox-compliance-mode) environment variable and re-check?

**Comment by antpyykk** [comment]
@krevedkokun , sorry for the late reply. We'll look into this and report the results.
Is this flag not enabled by default? Thanks for your input!

**Comment by krevedkokun** [comment]
@antpyykk it is disabled by default for backward compatibility
