### ISSUE TITLE
[BUG] profile folders doesn't collapse

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#534]
**Describe the bug**
When I click on a folder in the profile it expands, the second click doesn't collapse it back.

**Expected behavior**
The second click should collapse it.

**Screenshots**

**Versions:**
<img width="312" alt="Screenshot 2022-09-16 at 12 45 31" src="https://user-images.githubusercontent.com/1488983/190597020-795d4359-f8e3-4093-abac-51e5bf0f9a01.png">

 - Aidbox image version:
devbox:edge
v:2209.f8530dfd

**Comment by spicyfalafel** [comment]
Fixed
