### ISSUE TITLE
[BUG]  profile page reloads and content disappear

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#535]
**Describe the bug**
From time to time zen profile page reloads and content disappear, please see the video attached

**Screenshots**
https://user-images.githubusercontent.com/1488983/190597712-ac6302f3-bdb2-4547-a042-d14c3a860e62.mov

**Versions:**
devbox:edge
v:2209.f8530dfd

**Comment by VarvaraSemenova** [comment]
Fixed

**Comment by ir4y** [comment]
https://user-images.githubusercontent.com/1488983/191457107-304d8538-3bee-4eb5-9acd-cb2e0b8fd6f3.mov

**Comment by ir4y** [comment]
devbox:edge
v:2209.6d6c8e7b
