### ISSUE TITLE
[BUG] Aidbox console box-ui client access_token_expiration doesn't work

### ISSUE THREAD

**Issue by GenaRazmakhnin** [Aidbox/Issues#536]
**Describe the bug**
I want to set an expiration time for aidbox admin user session, but changing "box-ui" client configuration doesn't affect anything.

**Severity**
Minor

**Steps to reproduce the behavior:**
1. Login to aidbox admin console.
2. Change box-ui client configuration according to aidbox auth sandbox documentation
`access_token_expiration: 60`

**Expected behavior**
access_token_expiration attribute should affect aidbox console sessions. and session should be terminated in 1 minute

**Versions:**

 - Aidbox image version:
v:2207.32d6ec31 and upper

**Additional context**
<img width="1103" alt="Screenshot 2022-09-20 at 12 41 43" src="https://user-images.githubusercontent.com/9819783/191239570-96372321-2a53-4b23-a2a4-44ab788949cd.png">
<img width="582" alt="Screenshot 2022-09-20 at 11 56 12" src="https://user-images.githubusercontent.com/9819783/191239715-2bcc542b-215c-4d35-9781-1446ff37dcc0.png">

**Comment by ghost** [comment]
Aidbox does not use `Client` `box-ui` for its admin session but instead uses session of `User` `admin`. Currently it is not possible to set an expiration time for `User` sessions, you have to expire them manually.
