### ISSUE TITLE
Restrict SQL statement logging based on duration

### ISSUE THREAD

**Issue by matevarga** [Aidbox/Issues#537]
## Problem I need to solve
Aidbox is logging all SQL statements at INFO level. This can generate excessive (and uninteresting) log volumes. 

## Solution I see
I am only interested in long-running (problematic) queries, therefore I'd like to be able to set a lower bound on the duration of the queries that are logged at INFO level. The rest could / should only be logged at DEBUG level.

## Alternatives I've considered, but they don't work
-

## Additional context
Begin able to turn off query logging or move it to DEBUG level could also work as I could set up query logging on the DB side.

**Comment by ddegr** [comment]
We added the feature that allows one to get necessary Aidbox logs behaviour. Please, see [this documentation](https://docs.aidbox.app/modules-1/logging-and-audit/readme-1/set-up-logs-with-aidbox-project) and tell us if it helped
