### ISSUE TITLE
[BUG] csrf token is invalid on login page

### ISSUE THREAD

**Issue by PavanPatro-Innovaccer** [Aidbox/Issues#541]
**Describe the bug**
We are receiving CSRF token invalid error while accessing the aidBox using the client credentials. The error says " **CSRF token is invalid . This error may occur when multiple login pages were opened . Please, try to log-in again**" 
The behaviour is erratic though and causing a lot of issues. Have attached a screenshot for your reference .

<img width="1440" alt="Screenshot 2022-10-12 at 3 48 07 PM" src="https://user-images.githubusercontent.com/108468715/195325915-6cde4415-be9c-455f-9048-7792adf16db5.png">

**Severity**
Critical

**Steps to reproduce the behavior:**
login to https://roche-develop-fhir.innovaccer.net/
with client credentials :
Username /password:

-->

**Expected behavior**
To have a seamless login experience.

**Screenshots**

**Versions:**

 - Aidbox image version:
Edge

**Comment by krevedkokun** [comment]
hello, @PavanPatro-Innovaccer. it looks like you forgot to setup encryption key on that box. please follow steps described [here](https://docs.aidbox.app/api-1/encryption-api#configure-aidbox) and let us know if it fixed this issue for you

**Comment by krevedkokun** [comment]
@PavanPatro-Innovaccer we moved second bug to separate issue https://github.com/Aidbox/Issues/issues/542

**Comment by VarvaraSemenova** [comment]
Hi @PavanPatro-Innovaccer,
Do you have more than one replica for this Aidbox instanсe? If yes, you have to set up [BOX_AUTH_KEYS_SECRET](https://docs.aidbox.app/reference/configuration/environment-variables/optional-environment-variables#generate-secret) env to fix the issue
