### ISSUE TITLE
[BUG] "5XX" response code with a payload > 1Mb size

### ISSUE THREAD

**Issue by krevedkokun** [Aidbox/Issues#542]
lately we have observed, Whenever we are posting something to the AidBox (with a payload > 1Mb size, we get "5XX" as response code

**Severity**
???

**Steps to reproduce the behavior:**

**Expected behavior**

**Versions:**
edge

**Comment by krevedkokun** [comment]
@PavanPatro-Innovaccer

**Comment by Gorovoi** [comment]
@PavanPatro-Innovaccer, please could you provide the exact http error code and your http request which caused the error?

Could you also provide the current value of [BOX_WEB_MAX__BODY](https://docs.aidbox.app/reference/configuration/environment-variables/optional-environment-variables#box_web_max__body) env?

**Comment by VarvaraSemenova** [comment]
moved to another issue tracker

**Comment by VarvaraSemenova** [comment]
not affecting anymore.
