### ISSUE TITLE
Support for debugging dsql queries

### ISSUE THREAD

**Issue by vesnushka** [Aidbox/Issues#543]
## Problem I need to solve

We can't debug dsql queries through the Aidbox console. We are working on zen project where we write a lot of dsql queries.

## Solution I see

Add an option in the Aidbox console to allow the user to debug dsql queries.

**Comment by vesnushka** [comment]
Urgency: urgent

Example:
```
(lisp/sql {:select [:#>> :resource [:id]]
            :from :CareTeam
            :where [:and
                    [:=
                     [:#>> :resource [:subject :id]]
                     (lisp/sql
                      {:select [:#>> :resource [:subject :id]]
                       :from :Encounter
                       :where [:= :id (lisp/get-in [:params :encounter-id])]})]
                    [:=
                     [:#>> :resource [:status]]
                     "active"]]})
```


I see warning:
<img width="803" alt="Screenshot 2022-10-14 at 15 07 35" src="https://user-images.githubusercontent.com/11814124/195854582-7b55af97-8e2a-4435-84c6-7a5bb7da6c2f.png">


And I can't understand what should I fix to make this request work.  
I would like to be able to execute this expression step by step to trace the error.


<img width="1512" alt="Screenshot 2022-10-14 at 15 09 38" src="https://user-images.githubusercontent.com/11814124/195854950-fcae5cb8-823a-4afe-9597-1d65f006da6c.png">

**Comment by qdzo** [comment]
You are stying to use lisp/sql in DB console. But it only appropriate for using SQL/PLSQL code

Try using our RPC to call lisp/sql (in REST console)


```
POST /rpc
content-type: application/yaml

method: lisp/eval-lisp
params:
  data: <put your launch-ctx here as json/yaml obj>
  expr: '(lisp/sql {:select [:#>> :resource [:id]]
            :from :CareTeam
            :where [:and
                    [:=
                     [:#>> :resource [:subject :id]]
                     (lisp/sql
                      {:select [:#>> :resource [:subject :id]]
                       :from :Encounter
                       :where [:= :id (lisp/get-in [:params :encounter-id])]})]
                    [:=
                     [:#>> :resource [:status]]
                     "active"]]})'
 ```                    
                     
> Don't forget to wrap expression in quotes
