### ISSUE TITLE
Unable to view the log-in page 

### ISSUE THREAD

**Issue by PavanPatro-Innovaccer** [Aidbox/Issues#546]
We have deployed aidbox in our environment .
the env variable and our fhir server URL looks something as below:

AIDBOX_BASE_URL: https://roche-develop.innovaccer.net/fhirserver 
The base URL, when accessed, works absolutely fine.
However, when we try to access the auth end point i.e.  "https://roche-develop.innovaccer.net/fhirserver/auth/login" we get a broken web page 

<img width="1440" alt="Screenshot 2022-11-14 at 4 23 40 PM" src="https://user-images.githubusercontent.com/108468715/201831451-158adaf1-b1e0-4525-be60-9be54791775b.png">

could this be fixed on an urgent basis ?

**Comment by VarvaraSemenova** [comment]
Currently Aidbox expects base-url to be the domain without /path. Base urls with path are not supported yet, but you may raise an enhancement request if you need this to be supported.

**Comment by VarvaraSemenova** [comment]
@PavanPatro-Innovaccer hi, could you update us on the current state of the issue? will you wait till we support the paths as a part of our roadmap?

**Comment by VarvaraSemenova** [comment]
@PavanPatro-Innovaccer Released Aidbox [on path](https://docs.aidbox.app/reference/configuration/environment-variables/optional-environment-variables#aidbox_base_url). See [Release notes February 2023](https://docs.aidbox.app/overview/release-notes#february-2023-latest) 

Please try and let us know how it works for you!
