### ISSUE TITLE
_revinclude:iterate is not including the resources in the response

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#55]
In the following examples the resources targeted by the `_revinclude:iterate` are not returned:

GET -> `/fhir/Organization/org1/PractitionerRole?_include=PractitionerRole:practitioner&_revinclude:iterate=Appointment:practitioner`

GET -> `/fhir/DiagnosticReport?id=diag1&_include=DiagnosticReport:based-on&_revinclude:iterate=Task:based-on`

**Comment by capena1991** [comment]
I found that if you include the target type in the `revinclude`, it works. For example:
```
GET  /fhir/DiagnosticReport?id=diag1&_include=DiagnosticReport:based-on&_revinclude:iterate=Task:based-on:ServiceRequest
```

**Comment by niquola** [comment]
Yes, you have to specify source and target for chained (rev)includes!
Or use new _with parameter:

```yaml
GET  /fhir/DiagnosticReport?id=diag1&_with=based-on{ServiceRequest{Task.based-on}}
```
