### ISSUE TITLE
Support for overwriting fields when extending schema

### ISSUE THREAD

**Issue by Nitive** [Aidbox/Issues#551]
## I need the following improvement

I need to be able to overwrite some of the fields in FHIR resources schemas in my custom resources.

Let's say I need to extend [Communication resource](https://github.com/zen-fhir/hl7-fhir-r4-core/blob/main/zrc/hl7-fhir-r4-core/Communication.edn) to allow have references to `Person` in `sender` field.

I'm extending the schema like this

```edn
 Communication
 {:zen/tags #{zen/schema zen.fhir/base-schema}
  :type zen/map
  :zen.fhir/type "Communication"
  :zen.fhir/version "0.5.3"
  :confirms #{hl7-fhir-r4-core.Communication/schema}
  :keys {:sender
         {:confirms #{zenbox/Reference}
          :zen.fhir/reference
          {:refers
           #{hl7-fhir-r4-core.Person/schema
             hl7-fhir-r4-core.Patient/schema
             hl7-fhir-r4-core.PractitionerRole/schema
             hl7-fhir-r4-core.HealthcareService/schema
             hl7-fhir-r4-core.Organization/schema
             hl7-fhir-r4-core.Device/schema
             hl7-fhir-r4-core.Practitioner/schema
             hl7-fhir-r4-core.RelatedPerson/schema}}}
         :zen/desc "Message sender"}}}
```

But instead of validating the fields using the new schema the field is validated against both schemas

`resourceType: "Person"` (no validation messages expected)
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/6770225/209355827-35398dba-0c0d-41db-9c07-29c6bf63b279.png">

`resourceType: "BadInput"` (only 1 validation message expected)
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/6770225/209356185-688538ab-533b-4eb3-8d08-5cf05f12e7cf.png">

**Comment by Nesmeshnoy** [comment]
This will be resolved with FHIR Schema engine
