### ISSUE TITLE
[BUG]hl7Proxy utility-cannot change default port 5000.

### ISSUE THREAD

**Issue by vi123sb** [Aidbox/Issues#552]
**Describe the bug**

Cannot change the default port of 5000. Always goes back to listen on 5000.

**Severity**

Waiting to utilize this feature.
**Steps to reproduce the behavior:**

**Expected behavior**

**Screenshots**

**Versions:**

 - Aidbox image version:
 

**Additional context**

**Comment by mlapshin** [comment]
https://github.com/HealthSamurai/hl7proxy/releases/tag/port-bugfix
