### ISSUE TITLE
In the edge version, after the authentication it tries go to localhost

### ISSUE THREAD

**Issue by gmoraa** [Aidbox/Issues#554]
**Describe the bug**
In the edge version, after the authentication it tries go to localhost

**Severity**
Minor

**Steps to reproduce the behavior:**
1. Install `adibox:edge`
2. Proceed to login page
3. Authenticate

**Expected behavior**
Not to redirect to localhost

**Screenshots**
![image](https://user-images.githubusercontent.com/12487951/221281717-91624a22-8089-45f8-bc78-c2bf651201cd.png)

**Versions:**

 - Aidbox image version:
edge

**Additional context**
N/A

**Comment by VarvaraSemenova** [comment]
Resolution:

Please set correct value for AIDBOX_BASE_URL env.
Currently it has default value = localhost.

**Comment by VarvaraSemenova** [comment]
Fixed this behaviour on edge as well as in February 2023 latest release. 
See related documentation: Released Aidbox [on path](https://docs.aidbox.app/reference/configuration/environment-variables/optional-environment-variables#aidbox_base_url)
