### ISSUE TITLE
[BUG] Malformatted content-type returns server error

### ISSUE THREAD

**Issue by MFAshby** [Aidbox/Issues#555]
**Describe the bug**

A malformatted POST request with an invalid content-type sent to aidbox receives an error 500 response.

**Severity**

Low

**Steps to reproduce the behavior:**

The following cURL request reproduces the issue
```
curl -v -H "Content-Type: fehufiehdfefhesfhsefhsef" https://<server-url>/fhir/Foo -d '{}'
```
receives a response like this
```
< HTTP/2 500
< date: Wed, 01 Mar 2023 13:47:17 GMT
< content-length: 60
< strict-transport-security: max-age=15724800; includeSubDomains
<
Unknown/not supported Content-Type: fehufiehdfefhesfhsefhsef
```
**Expected behavior**

Error 400 Bad Request response should be returned

**Screenshots**

n/a
**Versions:**

 - Aidbox image version:
 

:edge
v:2210.f14920c0

**Additional context**

n/a

**Comment by spicyfalafel** [comment]
Fixed in 2302
