### ISSUE TITLE
Notify app/addon about subscription right after postgres transaction commit

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#56]
Currently, we have a bug when the app/addon receives a notification about a subscription when the resource is created inside a Bundle with type `transaction`. 

Example:
Our app/addon has a subscription for the Schedule resource.
The client creates a transaction bundle of Schedules (for example, 100 schedules) using Aidbox. Aidbox starts Postgres transaction and notifies app/addon right after first schedule creation. For this moment, the transaction might be not committed and it leads to unexpected behavior on the app/addon. For example, the app/addon tries to create Slot resources with reference to just created schedule and gets a validation error, because Schedule is not found in the database (because transaction hasn't been committed yet)

Possible solution:
Add app/addon subscriptions to the queue and run them right after the postgres transaction commit.

**Comment by KGOH** [comment]
Fixed in 0.5.0-SNAPSHOT.
