### ISSUE TITLE
[BUG] Can't click on logout button

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#560]
**Describe the bug**
The Aidbox version overlaps with the logout button on 1280x1024 screen size.

**Severity**
Major
It is not possible to log out

**Screenshots**
<img width="244" alt="Screenshot 2023-05-02 at 13 53 48" src="https://user-images.githubusercontent.com/1488983/235636292-c13c3e9e-660a-4501-8933-8724ed3fd442.png">

**Versions:**
 - Aidbox image version: stable

**Comment by ddegr** [comment]
fixed on :edge
