### ISSUE TITLE
[BUG] Error if ViewDefinition path contains capital letters

### ISSUE THREAD

**Issue by pavlushkin** [Aidbox/Issues#568]
**Describe the bug**
If use ViewDefinition path containing capital letters e.g. "ingredient.item.CodeableConcept"
get `ERROR: syntax error at or near "$" of jsonpath input`

**Severity**
Minor

**Steps to reproduce the behavior:**
Run ViewDefinition like
```json
{
  "description": "Medication flat view",
  "name": "medication_view",
  "extension": [
    {
      "url": "materialization",
      "value": {
        "code": "view"
      }
    }
  ],
  "status": "draft",
  "resource": "Medication",
  "select": [
    {
      "path": "id",
      "alias": "id"
    },
    {
      "path": "ingredient.item.CodeableConcept",
      "alias": "ingredient_strength"
    }
  ]
}
```

**Versions:**

 - Aidbox image version:
version: '2311'
channel: edge
commit: 1afd35ffc
zen-fhir-version: 0.6.30-1
timestamp: '2023-11-03T15:56:24Z'

**Additional context**
SQL-on-FHIR

**Comment by Nesmeshnoy** [comment]
@pavlushkin what's the severity?

**Comment by Yngwarr** [comment]
The idiomatic way to access polymorphic values in FHIR Path is to use `ofType` expression like so:

```
ingredient.item.ofType(CodeableConcept)
```

We will make the error message clearer, thank you for pointing this out.

**Comment by pavlushkin** [comment]
Thank you, that works!
