### ISSUE TITLE
_revinclude does not include resources on second tier references

### ISSUE THREAD

**Issue by rbagley0310** [Aidbox/Issues#57]
This works (it includes the org and/or the patient)

GET http://localhost:8888/Organization?_id=org-rich&_revinclude=Patient:organization
GET http://localhost:8888/Patient?_id=pat1&_include=organization

and this fails (only returns the main resource, not the included)

GET http://localhost:8888/Task?_id=8fc79cab-71c6-45b1-92a8-a3367e095149&_revinclude=DocumentReference:related
GET http://localhost:8888/DocumentReference?_id=e8047e6d-50bc-45f2-a087-af3b52f6ba5b&_include=related

The only seeming difference is that the property value is located one level down at **context.related**.

**Comment by niquola** [comment]
Try with 0.4.8-RC1. Should be fixed.
