### ISSUE TITLE
[BUG] Fail to create ServiceRequest with extensions in Notebook First-class extension tutorial.

### ISSUE THREAD

**Issue by utwoo** [Aidbox/Issues#572]
**Describe the bug**
Fail to creating service request with extensions in Notebook First-class extension tutorial.

**Severity**
Minor.

**Steps to reproduce the behavior:**
Open First-class extension tutorial in Notebook, and create service request extensions in order by the tutorial, when a new creating service request with extensions in last step, it throws OperationOutcome error.

**Expected behavior**
It should create a new service request without errors.

**Screenshots**
Create the ServiceRequest.performerInfo extension:
![image](https://github.com/Aidbox/Issues/assets/9206655/7bf4eafe-2e16-4dc5-bf16-8be37acbc7dd)

Throw OperationOutcome error when creating the service request
![image](https://github.com/Aidbox/Issues/assets/9206655/20378df4-077e-4340-9430-88c1c466abba)

**Versions:**

 - Aidbox image version:
:latest
v:2311.1d3d5b34

**Comment by VarvaraSemenova** [comment]
Hi @utwoo!  Please clarify if you are using any Aidbox project in your instance or just pass us the response of GET /$config request.
