### ISSUE TITLE
[BUG] AidboxQuery - Default value for type boolean doesn't work

### ISSUE THREAD

**Issue by zakharych** [Aidbox/Issues#574]
**Describe the bug**
Default value doesn't apply for parameter with boolean type.
I use query from : https://docs.aidbox.app/api-1/fhir-api/search-1/custom-search

**Steps to reproduce the behavior:**
Add new query :
```bash
PUT /AidboxQuery/debug

params:
  filter:
    isRequired: true
    type: string
    format: '%% %s%%'
  count:
    type: integer
    default: 10
  data:
    type: object
    default: {resourceType: 'Nop'}
  flag:
    default: true
    type: boolean
query: |
  SELECT 
   {{params.filter}}::text as filter,
   {{params.flag}} as flag,
   {{params.data}}::jsonb as data,
   {{params}}::jsonb as params,
   {{params.count}} as count,
   {{}} as ctx
count-query: |
  SELECT {{params.count}}
```

Run query:
```bash
GET /$query/debug?filter=ups&data=%7B%22a%22%3A%201%7D
```

**Expected behavior**
`flag = true`
But i got `flag = false`

**Screenshots**

![Screenshot from 2024-03-22 19-58-24](https://github.com/Aidbox/Issues/assets/56154852/3008ba56-1872-4f57-8f42-3650e764ff3c)

**Versions:**
version: '2403'
channel: edge
commit: 7f265503d

**Comment by letzabelin** [comment]
The issue is how the value for the boolean type is parsed. The value must be a string 'true'  to be parsed to boolean true

**Comment by letzabelin** [comment]
@zakharych 

The bug occurred due to a function that is responsible for translating values from one type to another

To get the value true, you had to explicitly specify the string 'true' as in the example below

```
 flag:
    default: 'true'
    type: boolean
```

Now the bug is fixed, you can check it in the "edge" version of aidbox. Now the examples from the documentation will work properly

```
PUT /AidboxQuery/debug

params:
  filter:
    isRequired: true
    type: string
    format: '%% %s%%'
  count:
    type: integer
    default: 10
  data:
    type: object
    default: {resourceType: 'Nop'}
  flag:
    default: true
    type: boolean
query: |
  SELECT 
   {{params.filter}}::text as filter,
   {{params.flag}} as flag,
   {{params.data}}::jsonb as data,
   {{params}}::jsonb as params,
   {{params.count}} as count,
   {{}} as ctx
count-query: |
  SELECT {{params.count}}
```
