### ISSUE TITLE
How to save logs to database

### ISSUE THREAD

**Issue by utwoo** [Aidbox/Issues#575]
## How to save logs to database

I want to save aidbox logs to aidbox postgres database, and I set _AIDBOX_DEVLOGS=true_ in .env but no logs pushed to the _logs table. Is there anything I missing in my configuration?

**Comment by vladzholnerchuk** [comment]
Hi @utwoo, my apologies for the late reply. The env doesn't work at the moment indeed, thank you for pointing it out. The task has been added to our backlog. Please, let me know how critical this is for you.
