### ISSUE TITLE
[BUG] - Broken links in documentation

### ISSUE THREAD

**Issue by brianlindsy** [Aidbox/Issues#577]
**Describe the bug**
In https://docs.aidbox.app/#modules, the links for Terminology Server and C-CDA/FHIR Converter seem to be broken and send me to a 404 page on github.

**Severity**
Low

**Steps to reproduce the behavior:**

**Expected behavior**

**Screenshots**

**Versions:**

 - Aidbox image version:
 

**Additional context**

**Comment by Nesmeshnoy** [comment]
Hi @brianlindsy it's fixed. Please check here https://docs.aidbox.app/
