### ISSUE TITLE
_include:iterate is not working when using Reference identifier

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#60]
The following request:

GET -> `/fhir/Organization/org1/PractitionerRole?_count=100&_totalMethod=count&practitioner=pract1&_include=PractitionerRole%3Apractitioner&_revinclude%3Aiterate=Appointment%3Apractitioner%3APractitioner&_include%3Aiterate=Appointment%3Apatient&_sort=-date`

It works when used [fhir references](https://www.hl7.org/fhir/references.html) with a [Reference string](https://www.hl7.org/fhir/references-definitions.html#Reference.reference), but if for example we have an Appointment participant like:

```
{
                        "actor": {
                            "type": "Patient",
                            "identifier": {
                                "value": "123456",
                                "system": "http://domain/patient-number"
                            }
                        },
                        "status": "accepted",
                        "required": "required"
},
```

then the request response is with 500 as status code and body:

```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "fatal",
            "diagnostics": "java.lang.NullPointerException: null\n at [empty stack trace]\n",
            "code": "exception"
        }
    ]
}
```

If we remove the `&_include%3Aiterate=Appointment%3Apatient` part of the url where including the patients, then it works. If we add the [`:logical`](https://docs.aidbox.app/api/history#_include-and-_revinclude) modifier it does not return the error, but neither the included Patients.

**Comment by niquola** [comment]
Done with :logical modifier in 0.4.8-RC1

**Comment by niquola** [comment]
https://docs.aidbox.app/basic-concepts/search-1/_include-and-_revinclude#logical-modifier
