### ISSUE TITLE
Support for LastN Observations

### ISSUE THREAD

**Issue by orlandow** [Aidbox/Issues#7]
https://www.hl7.org/fhir/observation-operations.html#lastn

> The lastn query meets the common need for searching for the most recent or last n=number of observations for a subject. For example, retrieving the last 5 temperatures for a patient to view trends or fetching the most recent laboratory results or vital signs. To ask a server to return the last n=number of observations, the lastn queryuses the normal search parameters defined for the Observation resource. However, rather than their normal use, they are interpreted as inputs - i.e.. instead of requiring that the resources literally contain the search parameters, they are passed to a server algorithm of some kind that uses them to determine the most appropriate matches.

**Comment by mlapshin** [comment]
Done in recent Aidbox version, already works in Cloud.

**Comment by orlandow** [comment]
Is this only available for the /fhir/ endpoint?

Aidbox' endpoint returns `Resource Observation/$lastn not found`
