### ISSUE TITLE
Aidbox allows to create date propety with wrong format

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#80]
```
POST /fhir/Patient

birthDate: 10-10-1980
```

*Response:* `Status: 201`
```
birthDate: 10-10-1980
id: 62c93041-4f76-4153-99f1-57cc597a7ba9
meta: {lastUpdated: '2019-04-16T20:26:02.754Z', versionId: '4'}
resourceType: Patient
```

According to the specs:
`
A date, or partial date (e.g. just year or year + month) as used in human communication. The format is YYYY, YYYY-MM, or YYYY-MM-DD, e.g. 2018, 1973-06, or 1905-08-23. There SHALL be no time zone. Dates SHALL be valid dates
`

**Comment by niquola** [comment]
Thank you for the report - fixed in 0.4.2-snapshot.

> Some people, when confronted with a problem, think "I know, I'll use regular expressions." Now they have two problems.
