### ISSUE TITLE
Error when creating a date property

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#81]
If a date property is created with the [correct format](https://www.hl7.org/fhir/datatypes.html#date), Aidbox returns an error:

```
POST /fhir/Patient

birthDate: 1980-10-10
```

*Response:* `Status: 422`
```
resourceType: OperationOutcome
id: invalid
text: {status: generated, div: 'Validation failed: [{:path [:birthDate], :message
    "expected type of string"}]'}
issue:
- {severity: fatal, code: invalid, diagnostics: 'Validation failed: [{:path [:birthDate],
    :message "expected type of string"}]'}
```

**Comment by niquola** [comment]
You have to use ' or " literal for a date - yaml does not understand it's a string:

```yaml
POST /fhir/Patient

birthDate: '1980-10-10'
```

**Comment by yosbeleg89** [comment]
@niquola I was checking the [specs](https://yaml.org/spec/1.2/spec.html) and I can see that the timestamp examples are unquoted:

![image](https://user-images.githubusercontent.com/13590619/56295131-4bb8bf00-60fa-11e9-9168-0c998793a987.png)

I think that probably that's why when we added with wrong format:
```
birthDate: 10-10-1980
```
it was recognized as string by Aidbox, and if used the correct one:
```
birthDate: 1980-10-10
```
Then it is a timestamp with `date` format and not a string in yaml and Aidbox complains because it expects a string.

**Comment by niquola** [comment]
FHIR does not use yaml :)

**Comment by niquola** [comment]
It's just coincidence notation in spec looks like yaml

**Comment by yosbeleg89** [comment]
@niquola  I mean yaml specs: https://yaml.org/spec/1.2/spec.html nor FHIR specs.

**Comment by niquola** [comment]
Oh, aidbox use common denominator of json and yaml - so only strings, bools and numbers. I will check our yaml parser - may make it work for yaml
