### ISSUE TITLE
Unable to upload synthea generated patients

### ISSUE THREAD

**Issue by TheZorkij** [Aidbox/Issues#87]
There seems to be an inconsistency of data structures. A `POST /fhir` request gives the following response on FHIR versions 3.0.1, 3.2.0, 3.3.0:
  
<pre>
{
 "resourceType": "OperationOutcome",
 "id": "46",
 "text": {
  "div": "Transaction failed at entry[4]"
 },
 "issue": [
  {
   "severity": "fatal",
   "code": "invalid",
   "diagnostics": "Validation failed: [
      {:path [:clinicalStatus], :message \"expected type of string\"}
      {:path [:verificationStatus], :message \"expected type of string\"}
      {:path [:encounter], :message \"extra property\"}
      {:path [:recordedDate], :message \"extra property\"}]"
  }
 ]
}
</pre>

Older versions of FHIR also return status 400.

**Comment by niquola** [comment]
Looks like versions mismatch - which FHIR version is in aidbox and which is for Synthea?
Please attach the failing resource body.

**Comment by TheZorkij** [comment]
Indeed it was, Synthea gives R4 output by default apparently, it works fine when the versions are matched correctly. Thanks @niquola! Do you want me to add a note that Aidbox supports FHIR 4.0.0 to the installation manual?
