### ISSUE TITLE
/metadata not supported

### ISSUE THREAD

**Issue by vadi2** [Aidbox/Issues#9]
http://hl7.org/fhir/http.html#capabilities

> Applications SHALL return a Capability Statement that specifies which resource types and interactions are supported for the GET command. If a 404 Unknown is returned from the GET, FHIR is not supported on the nominated service url.

**Comment by Aitem** [comment]
Hi @vadi2, thank you for your feedback
Capability Statement will release in Aidbox 0.3.2

**Comment by niquola** [comment]
See https://docs.aidbox.app/api/metadata

**Comment by vadi2** [comment]
Thanks!
