### ISSUE TITLE
Chaining search without specify ResourceType doesn't work

### ISSUE THREAD

**Issue by jyeros** [Aidbox/Issues#93]
I have a PractitionerRole and I want to search by the name of the practitioner. When I do 
`Get /PractitionerRole?practitioner.name=myname` the server response with statusCode 500.
I can do the search but I need to specify the ResourceType. For example
`Get /PractitionerRole?practitioner:Practitioner.name=myname` works

Summary
`Get /PractitionerRole?practitioner.name=myname` ❌ 
`Get /PractitionerRole?practitioner:Practitioner.name=myname` ✅

**Comment by niquola** [comment]
Because of potential performance problems, we are not going to support this. It can bring 100X performance penalty.
